#!/bin/bash

DEBUG=
DEBUG=echo

ADDRESS=$1

echo removing $ADDRESS

USERS="tmdauser tmdatech tmdaweb tmdaiesg tmdaage tmdaipr tmdastat"
USERS=`grep tmda /etc/passwd | awk -F: '{print $1}'`
#USER="tmdauser"

for MUSER in $USERS; do
  # check for confirmed
  CBASE="/home/${MUSER}/.tmda/lists/confirmed"
  echo cheking $CBASE
  grep $ADDRESS $CBASE > /dev/null 2>&1
  if [ $? == 0 ]; then
        echo its in there $CBASE
        cp -p $CBASE /tmp/`basename $CBASE`
        grep -v $ADDRESS /tmp/`basename $CBASE` > $CBASE
#       /bin/rm /tmp/`basename $CBASE`
  fi
done
grep $ADDRESS /home/tmdauser/.tmda/lists/whitelist
cp -p /home/tmdauser/.tmda/lists/blacklist /tmp/
echo $ADDRESS >> /home/tmdauser/.tmda/lists/blacklist


