#!/bin/sh - 
#
# usage: archive-mail wg-acronym {-textsecure | -text | -both | -web}
# message as standard input

UNSECURE_ARCHIVE=/usr/IETF/mail-archive/text
SECURE_ARCHIVE=/usr/IETF/mail-archive/text-secure
UNSECURE_WEB_ARCHIVE=/usr/IETF/mail-archive/web
SECURE_WEB_ARCHIVE=/usr/IETF/mail-archive/web-secure
WEB_ARCHIVE_FILE_NAME=current.mail
TEXT_ARCHIVE_FILE_NAME=current

WG="$1"					#The workgroup that owns the message
MESSAGE_LOCK=/home/mail-archive/${WG}-temp.message
ARCHIVE_STYLE="$2"			#What kind of archive
THE_MESSAGE=(/bin/cat -)		#The message to archive

DEBUGFILE=/tmp/debug
touch $DEBUGFILE

archive_message() #Takes the destination directory (without working group) as a paramaeter
{
   WG_ARCHIVE_DIR="$1/$WG"
   if [ ! -d $WG_ARCHIVE_DIR ] ; then
       /bin/mkdir $WG_ARCHIVE_DIR
   fi
   ARCHIVE_FILE="$WG_ARCHIVE_DIR/$2"
   if [ ! -f "$ARCHIVE_FILE" ] ; then
        /bin/touch "$ARCHIVE_FILE"
   fi
   /bin/cat "$MESSAGE_LOCK" >> "$ARCHIVE_FILE"
   /bin/rm -f $MESSAGE_LOCK
}

global_lock()
{
   echo `date` checking for lock file at $MESSAGE_LOCK >> $DEBUGFILE
   while [ -f "$MESSAGE_LOCK" ] ; do
	/bin/sleep 2;
	/usr/bin/Mail -s "sleeping on $WG `date`" ietf-admin@techsquare.com < /dev/null > /dev/null 2>&1
   done
   /bin/touch "$MESSAGE_LOCK"
   echo `date` created lock file at $MESSAGE_LOCK >> $DEBUGFILE

}

validate_message()
{
    (/bin/cat - | /usr/bin/procmail -m LIST=$WG /usr/IETF/scripts/proc-pw-filter;) >> "$MESSAGE_LOCK"
   if [ -s $MESSAGE_LOCK ] ; then
      (echo ''; echo '';) >> "$MESSAGE_LOCK"
#   else
#      /bin/rm $MESSAGE_LOCK
#      exit 0
   fi
   echo "MESSAGE START" >> $DEBUGFILE
   cat $MESSAGE_LOCK >> $DEBUGFILE
   echo "MESSAGE END" >> $DEBUGFILE
}

#MAIN PROGRAM
echo "starting `/bin/date`" >> $DEBUGFILE
global_lock
validate_message


/bin/date >> $DEBUGFILE
echo $WG >> $DEBUGFILE
echo "foo"
echo $MESSAGE_LOCK >> $DEBUGFILE
echo "foo"
echo $ARCHIVE_STYLE >> $DEBUGFILE
echo "foo"
echo $THE_MESSAGE >> $DEBUGFILE
echo "foo"
date >> $DEBUGFILE


case $ARCHIVE_STYLE in
   -textsecure)
	#nomcom, new-work, iesg / MAIL_ARCHIVES
	archive_message $SECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	if (test $WG = "iesg"); then
	   WG=MAIL_ARCHIVES
	fi
	#echo "textsecure"
	;;
   -text)
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	#echo "text"
	;;
   -both)
	#This if for unsecured archives only.  Need something different?  Write it!
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	archive_message $UNSECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "both"
	;;
   -websecure)
	archive_message $SECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "websecure"
	;;
   -web)
	archive_message $UNSECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "web"
	;;
   *)
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	#echo "junkyard"
	;;
esac
exit 0
