#!/bin/sh - 
#
# usage: archive-mail wg-acronym {-textsecure | -text | -both | -web}
# message as standard input

PATH=$PATH:/bin:/usr/bin
export PATH

#SYSTEM CONSTANTS (Sendmail exit codes /usr/include/sysexits.h)
EX_NOUSER=67
EX_TEMPFAIL=75

#PROGRAM CONSTANTS
UNSECURE_ARCHIVE=/usr/IETF/mail-archive/text
SECURE_ARCHIVE=/usr/IETF/mail-archive/text-secure
UNSECURE_WEB_ARCHIVE=/usr/IETF/mail-archive/web
SECURE_WEB_ARCHIVE=/usr/IETF/mail-archive/web-secure
WEB_ARCHIVE_FILE_NAME=current.mail
TEXT_ARCHIVE_FILE_NAME=current

#PROGRAM VARIABLES
WG="$1"					#The workgroup that owns the message
MESSAGE_LOCK=/home/mail-archive/${WG}-temp.message
ARCHIVE_STYLE="$2"			#What kind of archive
THE_MESSAGE=(/bin/cat -)		#The message to archive
TEMP_MESSAGE=/var/tmp/${WG}-the_message.$$
/bin/touch $TEMP_MESSAGE 2>&1

DEBUGFILE=/tmp/debug
touch $DEBUGFILE

archive_message()
{
   echo "start archive_message" >> $DEBUGFILE 2>&1
   WG_ARCHIVE_DIR="$1/$WG"
   if [ ! -d $WG_ARCHIVE_DIR ] ; then
       /bin/mkdir $WG_ARCHIVE_DIR
   fi
   ARCHIVE_FILE="$WG_ARCHIVE_DIR/$2"
   if [ ! -f "$ARCHIVE_FILE" ] ; then
        /bin/touch "$ARCHIVE_FILE"
   fi
   /bin/cat "$TEMP_MESSAGE" >> "$ARCHIVE_FILE"
#   /bin/rm -f $TEMP_MESSAGE > /dev/null 2>&1
   /bin/rm -f $MESSAGE_LOCK > /dev/null 2>&1
   echo "end archive_message" >> $DEBUGFILE 2>&1
}

global_lock()
{
   echo "start global_lock" >> $DEBUGFILE 2>&1
   while [ -f "$MESSAGE_LOCK" ] ; do
	/bin/sleep 5;
#	/usr/bin/Mail -s "sleeping on $WG $TEMP_MESSAGE `date`" ietf-logs@techsquare.com < /dev/null > /dev/null 2>&1
   done
   /bin/touch "$MESSAGE_LOCK"
   echo "end global_lock" >> $DEBUGFILE 2>&1
}

validate_message()
{
   echo "start validate_message" >> $DEBUGFILE 2>&1
   ((/bin/cat - | /usr/bin/procmail -m LIST=$WG /usr/IETF/scripts/proc-pw-filter2;) >> "$TEMP_MESSAGE") >> $DEBUGFILE 2>&1
   if [ -s $TEMP_MESSAGE ] ; then
      (echo ''; echo '';) >> "$TEMP_MESSAGE" 2>&1
   else
      /bin/rm $TEMP_MESSAGE > /dev/null 2>&1
      exit 0
   fi
   echo "end validate_message" >> $DEBUGFILE 2>&1
}

echo "starting `/bin/date`" >> $DEBUGFILE 2>&1
#MAIN PROGRAM
validate_message
global_lock

case $ARCHIVE_STYLE in
   -textsecure)
	#nomcom, new-work, iesg / MAIL_ARCHIVES
	archive_message $SECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	if (test $WG = "iesg"); then
	   WG=MAIL_ARCHIVES
	fi
	#echo "textsecure"
	;;
   -text)
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	#echo "text"
	;;
   -both)
	#This if for unsecured archives only.  Need something different?  Write it!
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	archive_message $UNSECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "both"
	;;
   -websecure)
	archive_message $SECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "websecure"
	;;
   -web)
	archive_message $UNSECURE_WEB_ARCHIVE $WEB_ARCHIVE_FILE_NAME
	#echo "web"
	;;
   *)
	archive_message $UNSECURE_ARCHIVE $TEXT_ARCHIVE_FILE_NAME
	#echo "junkyard"
	;;
esac
echo "ending `/bin/date`" >> $DEBUGFILE 2>&1
exit 0
