#!/bin/bash

DATE=`date '+%w'`
FILENAME=/usr/exim/log/report.$DATE.txt

/usr/exim/bin/exim_tidydb -t 3d /usr/exim/spool retry > /dev/null

cat /usr/exim/log/mainlog.01 | /usr/exim/bin/eximstats -t10 -nr > $FILENAME

mail -s "eximlog [`hostname`] `date '+%Y-%m-%d'`" logs < $FILENAME

if [ $DATE -eq 0 ]; then
	WEEK=`date '+%W'`
	WEEKFILENAME=/usr/exim/log/week.$WEEK.txt
	/usr/exim/bin/eximstats -merge /usr/exim/log/report*.txt > $WEEKFILENAME
	mail -s "eximlog [`hostname`] `date '+%Y-%m-%d'`" logs < $WEEKFILENAME
fi

