# Copyright The IETF Trust 2021 All Rights Reserved
# Generated by Django 2.2.19 on 2021-04-02 12:03

from django.db import migrations


def forward(apps, schema_editor):
    AgendaFilterTypeName = apps.get_model('name', 'AgendaFilterTypeName')
    names = (
        ('none', 'None', 'Not used except for a timeslot-type column (e.g., officehours)'),
        ('normal', 'Normal', 'Non-heading filter button'),
        ('heading', 'Heading', 'Column heading button'),
        ('special', 'Special', 'Button in the catch-all column'),
    )
    for order, (slug, name, desc) in enumerate(names):
        AgendaFilterTypeName.objects.create(slug=slug, name=name, desc=desc, order=order, used=True)


def reverse(apps, schema_editor):
    pass  # nothing to do, model about to be destroyed anyway


class Migration(migrations.Migration):
    dependencies = [
        ('meeting', '0042_meeting_group_conflict_types'),  # fix interleaving
        ('name', '0028_agendafiltertypename'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
