# Copyright The IETF Trust 2019, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 13:12
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, shema_editor):
    Recipient = apps.get_model('mailtrigger','Recipient')

    irsg = Recipient.objects.create(
        slug = 'irsg',
        desc = 'The IRSG',
        template = 'irsg@irtf.org'
    )

    MailTrigger = apps.get_model('mailtrigger', 'MailTrigger')
    slug = 'irsg_ballot_saved'
    desc = 'Recipients when a new IRSG ballot position with comments is saved'
    irsg_ballot_saved = MailTrigger.objects.create(
        slug=slug,
        desc=desc
    )
    irsg_ballot_saved.to.add(irsg)

def reverse(apps, shema_editor):
    MailTrigger = apps.get_model('mailtrigger', 'MailTrigger')
    MailTrigger.object.filter(slug='irsg_ballot_saved').delete()

    Recipient = apps.get_model('mailtrigger','Recipient')
    Recipient.object.filter(slug='irsg').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mailtrigger', '0012_dont_last_call_early_reviews'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
