#!/bin/bash

DATESTR=`date '+%Y-%m-%d'`
LOGFILE=/tmp/rfc.$$
DRAFTS=/var/ftp/internet-drafts

if [ -d $DRAFTS ]; then

cd $DRAFTS

COUNT=`find . -perm +o+w -ls | wc -l`

if [ $COUNT -ne 0 ]; then
        echo these files are world writable
        find . -perm +o+w -ls
fi

/bin/mail -s "$0 `hostname` $DATESTR" logs < $LOGFILE

/bin/rm -f $LOGFILE

fi

