#!/bin/bash

umask 000

MESSAGE_LOCK=/a/www/ietf-mail-archive/temp.message
ARCHIVEDIR="/a/www/ietf-mail-archive/text"
ARCHIVELIST=`cd $ARCHIVEDIR && \ls -1 | xargs`

DATESTR=`date -d "1 month ago" '+%Y-%m-%d'`
FILENAME="`date -d "1 month ago" '+%Y-%m'`.mail"

echo starting rotate on `date`
for MAILLINGLIST in $ARCHIVELIST; do
        echo ---- $MAILLINGLIST ----
        while [ -f $MESSAGE_LOCK ];do
                echo sleeping on $MAILLINGLIST
                sleep 10;
        done
        touch $MESSAGE_LOCK
        cd $ARCHIVEDIR/$MAILLINGLIST
        if [ ! -s current ]; then
            echo $MAILLINGLIST current is empty
        fi
        if [ ! -f $FILENAME ]; then
            cp current $FILENAME
            cat /dev/null > current
	    chmod 666 current
        else
            echo cant rotate $MAILLINGLIST already $FILENAME
        fi
        rm -f $MESSAGE_LOCK
done
echo done rotate on `date`

MESSAGE_LOCK=/a/www/ietf-mail-archive/temp.message
ARCHIVEDIR="/a/www/ietf-mail-archive/text-secure"
ARCHIVELIST=`cd $ARCHIVEDIR && \ls -1 | xargs`

DATESTR=`date -d "1 month ago" '+%Y-%m-%d'`
FILENAME="`date -d "1 month ago" '+%Y-%m'`.mail"

echo starting rotate on `date`
for MAILLINGLIST in $ARCHIVELIST; do
        echo ---- $MAILLINGLIST ----
        while [ -f $MESSAGE_LOCK ];do
                echo sleeping on $MAILLINGLIST
                sleep 10;
        done
        touch $MESSAGE_LOCK
        cd $ARCHIVEDIR/$MAILLINGLIST
        if [ ! -s current ]; then
            echo $MAILLINGLIST current is empty
        fi
        if [ ! -f $FILENAME ]; then
            cp current $FILENAME
            cat /dev/null > current
	    chmod 666 current
        else
            echo cant rotate $MAILLINGLIST already $FILENAME
        fi
        rm -f $MESSAGE_LOCK
done
echo done rotate on `date`



