#!/usr/bin/perl
##########################################################################
# Copyright © 2002, Foretec Seminars, Inc.
##########################################################################
use lib '/a/www/ietf-datatracker/release/';
use GEN_UTIL;
use IETF;

#########################################################################
#                                                                       #
#       Last modified by Michael Lee: Jan 24, 2002                      #
#              ---- PDF file type                                       #
#                                                                       #
#########################################################################

# THE FILE THAT THIS PROGRAM TAKES AS INPUT IS "1id-abstracts.txt".

# Constants
$FALSE=0;
$TRUE=1;
@MONTHS=("January", "February", "March", "April", "May", "June", "July",
	"August", "September", "October", "November", "December");
@DAYS=("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
	"Saturday", "Sunday");

# Get program name
@path_components = split(/\//, $0);
$program_name = $path_components[$#path_components];

# Check on the input file
$infilename=$ARGV[0];

# The output file will be the basename (filename only -- no leading
# path) of the input file with the extension changed to "html".
@path_components = split(/\//, $infilename);
$dummy_string = $path_components[$#path_components];
$dummy_string =~ s/(.+)\..*/$1/;
$outfilename="${dummy_string}.html";
undef $dummy_string;

# See about outfile
if ( -f $outfilename )
	{
	if (! unlink("$outfilename"))
		{
		print "EXITING -- $outfilename exists and I can't delete it.\n";
		exit(1);
		}
	}

# Check on the destination directory
$dest_dir="ids.by.wg";
$dest_dir =~ s/\/$//;

open(INFILE,"< $infilename") ||
	die "$program_name: unable to open $infilename ($!)\n";
open(OUTFILE,"> /a/www/ietf/$outfilename") ||
	die "$program_name: unable to open $outfilename ($!)\n";

# Get the title
$_=<INFILE>;
while ($_ eq "\n")
	{
	$_=<INFILE>;
	}
chop;
# Get rid of leading spaces
s/\s*(.+)/$1/;
print OUTFILE "<html>\n";
print OUTFILE "<head>\n";
print OUTFILE "<title>$_</title>\n\n";
print OUTFILE "</head>\n";

&Print_New_Header;

print OUTFILE "<h1>$_</h1>\n\n";
# Print some intro stuff
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();
print OUTFILE <<"_END_";
<B>
This list and the associated sub-lists were generated on
_END_
$year=$year+1900;
printf (OUTFILE " %s %d %s %d at %0.2d:%0.2d:%0.2d.<p>\n",$DAYS[$wday],
	$mday,$MONTHS[$mon],$year,$hour,$min,$sec);
print OUTFILE <<"_END_";
If you find errors, please notify <i> <a href="mailto:internet-drafts\@ietf.org">The I-D Administrator</a></i>.
</B>
<HR>
Note that Internet-Drafts which are not associated with an
IETF working group are collected into the "Individual Submissions"
item at the bottom of the list.
<HR>
_END_


# Get the introductory paragraph
$_=<INFILE>;
while ($_ eq "\n")
	{
	$_=<INFILE>;
	}
$intro_paragraph=$_;
$_=<INFILE>;
while ($_ ne "\n")
	{
	$intro_paragraph .= $_;
	$_=<INFILE>;
	}
chop $intro_paragraph;
print OUTFILE "$intro_paragraph <p>\n";
print OUTFILE "\n<ul>\n";

# Read past the extra blank line
$_=<INFILE>;

# This is the loop that does the real work
$current_wg="**FIRST**";
$done=$FALSE;
$wg_title_line=<INFILE>;
while (! $done)
	{
#        $wg_title_line =~ /([^\(]+)\(([^\)]+)\)/;
#	$wg_name=$1;
#	$wg_acronym=$2;
        $wg_title_line = reverse $wg_title_line ;
        ($wg_acronym, $wg_name) = split ' ', $wg_title_line, 2 ;
         chop $wg_acronym ;
         $wg_name = reverse $wg_name ;
        $wg_acronym = reverse $wg_acronym ;
        chop $wg_acronym ;

	$in_dummy_working_group=$FALSE;
	if ($wg_acronym eq "none")
		{
		$in_dummy_working_group=$TRUE;
		}
	$id_count=1;
	open(WG_OUTFILE,"> /a/www/ietf/${dest_dir}/${wg_acronym}.html") ||
		die "$program_name: can't open ${dest_dir}/${wg_acronym} ($!)\n";

################
	&Print_New_WG_Header;
################

	print WG_OUTFILE "<dl>\n";
	if (! $in_dummy_working_group)
		{
		print OUTFILE <<"__END__";
<li> <A HREF=${dest_dir}/${wg_acronym}.html>$wg_name ($wg_acronym)</A> -- 
__END__
		}
	else
		{
		$none_string=<<"__END__";
<li> <A HREF=${dest_dir}/${wg_acronym}.html>Individual Submissions</A> --
__END__
		}
	# Read the line of dashes, the following blank line, and 1st bibl line
	$_=<INFILE>;	# line of dashes
	$_=<INFILE>;	# blank line
	$_=<INFILE>;	# first line of bibl
	$done_wg=$FALSE;

	$id_count=0;
	while (! $done_wg)
		{
		$id_count++;
		# Read the bibliographic entry
		chop;
		$bibl=$_;
		$_=<INFILE>;

		while ($_ ne "\n")
			{
			chop;
			$bibl .= $_;
			$_=<INFILE>;
			}
		# Remove leading white-space
		$bibl =~ s/^\s*//;
		# ...and trailing white-space
		$bibl =~ s/\s*$//;
		# Grab the pathname, delimeted by '<' and '>'
		$bibl =~ /([^<]+)<([^>]+)>/;
		# Set the bibliography to everything but the pathname
		$bibl=$1;
		# ...and grab just the pathname
		$id_pathname=$2;
		# Remove trailing white-space
		$bibl =~ s/\s*$//;
		# ...and the trailing comma
		chop $bibl;
		# ...and tack on a period to make it "proper"
		$bibl .= ".";
		($path, $suffix) = split(/\./,$id_pathname,2);
		$postscript=$FALSE;
		$pdf = $FALSE;
		if ($suffix =~ /txt,\s*.ps/)
			{
			$postscript=$TRUE;
			$id_pathname="${path}.txt";
			}
		if ($suffix =~ /txt,\S*.pdf/)
			{
			$pdf=$TRUE;
			$id_pathname="${path}.txt";
			}
		# Figure out how long the .txt file is
		($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$bytes,$atime,
			$mtime,$ctime,$blksize,$blocks) =
			stat("/ftp/internet-drafts/${path}.txt");
		# ...and, if necessary, how long the .ps file is
		if ($postscript)
			{
			($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$ps_bytes,$atime,
				$mtime,$ctime,$blksize,$blocks) =
				stat("/ftp/internet-drafts/${path}.ps");
			}
		# ...and, if necessary, how long the .pdf file is
		if ($pdf)
			{
			($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$pdf_bytes,$atime,
				$mtime,$ctime,$blksize,$blocks) =
				stat("/ftp/internet-drafts/${path}.pdf");
			}
		print WG_OUTFILE <<"__END__";
<dt> <A HREF="/internet-drafts/${id_pathname}">
$bibl ($bytes bytes)</A>
__END__
		# Read the abstract
		$abstract="";
		$_=<INFILE>;
		while ($_ !~ /^\s$/)
			{
			$abstract .= $_;
			$_=<INFILE>;
			}
		chop $abstract;
		print WG_OUTFILE "<dd> $abstract";
		if ($postscript or $pdf) {
			$diff_format = qq {
			(This Internet-Draft is also available in};
			if ($postscript) {
			   $diff_format .= qq {<A HREF="/internet-drafts/${path}.ps">
PostScript format</A> [$ps_bytes bytes].};
			}
			if ($pdf) {
			   $diff_format .= qq {<A HREF="/internet-drafts/${path}.pdf">
PDF format</A> [$pdf_bytes bytes].};
			}
			$diff_format .= qq {)
			};
			print WG_OUTFILE  $diff_format;
		}
		print WG_OUTFILE "\n";
		$_=<INFILE>;
		if ($_ !~ /^  "/)
			{
			$done_wg=$TRUE;
			}
                # Added by Michael Lee to detect unknown character in blank line
		#if (length($_) < 5) {
   			#$done_wg = $FALSE;
		#}
		# Added by Michael Lee to prevent the process from hanging due to the abnormal ending
		$done_wg = $TRUE unless ($_);
#last if (id_count > 100);
	    }
	print WG_OUTFILE<<"_END_HTML_";
</dl>

<HR>

<I> IETF Secretariat - Please send questions, comments, and/or 
suggestions to </I> <a href="mailto:ietf-web\@ietf.org">ietf-web\@ietf.org</a>.
<P>

<A HREF="/1id-abstracts.html">
<IMG SRC="/images/back.gif"> Return to Internet-Draft directory. </A> <P>

<A HREF="/home.html">
<IMG SRC="/images/back.gif"> <IMG SRC="/images/back.gif">
Return to IETF home page. </A>

</body>
</html>

_END_HTML_

	close(WG_OUTFILE);
	if (! $in_dummy_working_group)
		{
		print OUTFILE "$id_count Internet-Drafts\n\n";
		}
	else
		{
		$none_string .= "$id_count Internet-Drafts\n\n";
		}
	$wg_title_line=$_;
	$done=$TRUE if ($_ eq "\n");
        $done = $TRUE unless ($_); ##Added by Michael Lee 3/5/2002, terminate the process if EOF
#last if (id_count > 100);
	}

print OUTFILE<<"_END_HTML_";
$none_string
</ul>

<HR>

<I> IETF Secretariat - Please send questions, comments, and/or 
suggestions to </I> <a href="mailto:ietf-web\@ietf.org">ietf-web\@ietf.org</a>.
<P>

<A HREF="/home.html">
<IMG SRC="/images/back.gif"> Return to IETF home page. </A>

</body>
</html>

_END_HTML_

close(OUTFILE);

##########################################

sub Print_New_Header{

print OUTFILE<<"ENDOFHEADER";

<!-- begin new headers and page layout -->
<body bgcolor="#ffffff">
<center>
<table border=0 cellpadding=0 cellspacing=0>
<tr>
<td><a href="/home.html"><img src="/images/header/ietflogo_sm.gif" border="0"></a></td>
<td><a href="/home.html"><img src="/images/header/home11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/html.charters/wg-dir.html"><img src="/images/header/wg11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/meetings/meetings.html"><img src="/images/header/meetings11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/proceedings/directory.html"><img src="/images/header/proceed11.gif"  border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/ID.html"><img src="/images/header/id-index11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/rfc.html"><img src="/images/header/rfc11.gif" border="0"></a></td>
</tr>
</table>
</center>
<hr>
<!-- end new headers and layout -->

ENDOFHEADER
}

##########################################

sub Print_New_WG_Header{

print WG_OUTFILE<<"ENDOFHEADER";

<!-- begin new headers and page layout -->
<body bgcolor="#ffffff">
<br>
<center>
<table border=0 cellpadding=0 cellspacing=0>
<tr>
<td><a href="/home.html"><img src="/images/header/ietflogo_sm.gif" border="0"></a></td>
<td><a href="/home.html"><img src="/images/header/home11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/html.charters/wg-dir.html"><img src="/images/header/wg11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/meetings/meetings.html"><img src="/images/header/meetings11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/proceedings/directory.html"><img src="/images/header/proceed11.gif"  border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/ID.html"><img src="/images/header/id-index11.gif" border="0"></a></td>
<td><img src="/images/header/separator.gif" border="0"></td>
<td><a href="/rfc.html"><img src="/images/header/rfc11.gif" border="0"></a></td>
</tr>
</table>
</center>
<hr>
<!-- end new headers and layout -->

ENDOFHEADER
}
