#!/usr/bin/perl
##########################################################################
# Copyright © 2002, Foretec Seminars, Inc.
##########################################################################

use lib '/a/www/ietf-datatracker/release/';
use GEN_UTIL;
use GEN_DBUTIL;
use IETF;

init_database("ietf");

my $sqlStr = qq {
  select a.acronym,a.name,a2.name from acronym a,acronym a2,groups_ietf g, area_group c 
  where g.group_acronym_id = a.acronym_id
  and g.group_type_id = 1
  and g.status_id = 1
  and g.group_acronym_id=c.group_acronym_id
  and c.area_acronym_id = a2.acronym_id
};
if (defined($ARGV[0]) and $ARGV[0] eq "-byacronym") {
  $sqlStr .= qq{  order by a.acronym
};
} else {
  $sqlStr .= qq{  order by a2.name, a.name
};
}
my @List = db_select_multiple($sqlStr);
open OUTFILE,">/tmp/1wg-charter.txt";

for $array_ref (@List) {
  my ($group_acronym) = @$array_ref;
  print OUTFILE "$group_acronym\n";
}
close OUTFILE;
for $array_ref (@List) {
  my ($group_acronym) = @$array_ref;
  system "/a/ietf/scripts/update-web-pages-wginfo $group_acronym -description -id >> /tmp/1wg-charter.txt";

}
system "cat /tmp/1wg-charter.txt;rm /tmp/1wg-charter.txt";

exit;   


