# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# ietf.sidemeeting.migrations.0005_addsidemeetingtypenamedata

TYPES = ["IETF", "IRTF", "IAB", "Corporate", "Non-profit"]

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SideMeetingTypeName = apps.get_model("meeting", "SideMeetingTypeName")
    db_alias = schema_editor.connection.alias
    SideMeetingTypeName.objects.using(db_alias).bulk_create(
        [ SideMeetingTypeName(name=t, slug=t.lower()) for t in TYPES ]
    )
        
def reverse_func(apps, schema_editor):
    SideMeetingTypeName = apps.get_model("meeting", "SideMeetingTypeName")
    db_alias = schema_editor.connection.alias
    SideMeetingTypeName.objects.using(db_alias).filter(name__in=TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20170301_0332'),
        ('meeting', '0052_floorplan_short'),
#        ('meeting', '0049_auto_20170508_0638'),        
    ]

    operations = [
        migrations.CreateModel(
            name='SideMeetingTypeName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('used', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('test', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideMeetingSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.Session')),
                ('requested_prim_start_date', models.DateTimeField()),
                ('requested_alt_start_date', models.DateTimeField()),
                ('sidemeeting_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meeting.SideMeetingTypeName')),                
                ('requested_start_time', models.CharField(default=1, max_length=5)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
            bases=('meeting.session',),
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=reverse_func,
        ),
    ]
