# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0053_sidemeeting'),
        ('meeting', '0049_auto_20170508_0638'),
    ]

    operations = [
    ]
