# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_remove_reviewrequest_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsecretarysettings',
            name='days_to_show_in_reviewer_list',
            field=models.IntegerField(blank=True, help_text=b'Maximum number of days to show in reviewer list for completed items.', null=True),
        ),
        migrations.AddField(
            model_name='reviewsecretarysettings',
            name='max_items_to_show_in_reviewer_list',
            field=models.IntegerField(blank=True, help_text=b'Maximum number of completed items to show for one reviewer in the reviewer list view, the list is also filtered by the days to show in reviews list setting.', null=True),
        ),
    ]
