# Copyright The IETF Trust 2018-2019, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0024_add_irsg_doc_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballotpositiondocevent',
            old_name='ad',
            new_name='pos_by',
        ),
    ]
