# Copyright The IETF Trust 2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0029_add_ipr_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth48StateDocEvent',
            fields=[
                ('statedocevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doc.StateDocEvent')),
                ('auth48_url', models.URLField()),
            ],
            bases=('doc.statedocevent',),
        ),
    ]
