#!/bin/bash

version=0.20
program=${0##*/}
progdir=${0%/*}
if [ "$progdir" = "$program" ]; then progdir="."; fi
if [ "$progdir" = "." ]; then progdir="$PWD"; fi
parent=$(dirname $progdir)
if [ "$parent" = "." ]; then parent="$PWD"; fi
if [[ $(uname) =~ CYGWIN.* ]]; then parent=$(echo $parent | sed -e 's/^\/cygdrive\/\(.\)/\1:/'); fi

# ----------------------------------------------------------------------
function usage() {
    cat <<EOF
NAME
    $program - Run a docker datatracker container with suitable settings

SYNOPSIS
    $program [OPTIONS] ARGS

DESCRIPTION

    This is a wrapper which runs docker with suitable arguments on a
    debian-based docker image which has been set up with the dependencies
    needed to easily run the IETF datatracker in development mode.  By
    default, it expects to find the MySQL database files at
    $parent/data/mysql, which is mapped inside the
    container to /var/lib/mysql, and it will set up a home directory for
    the current user ($USER) and map it to $HOME.

EOF
    echo -e "OPTIONS"
    if   [ "$(uname)" = "Linux" ]; then
        egrep "^[   ]+[-][A-Za-z| -]+\*?\)[ ]+[A-Za-z].+#" $0 | tr -s "\t|" "\t," | sed -r -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
    else
        egrep "^[   ]+[-][A-Za-z| -]+\*?\)[ ]+[A-Za-z].+#" $0 | sed 's/\|.*\$2[^#]*#/   /'| sed -E 's/\|.*\)[^#]*#/ /'
    fi
    cat <<EOF

FILES

AUTHOR
    Written by Henrik Levkowetz, <henrik@levkowetz.com>

COPYRIGHT

    Copyright (c) 2015 IETF Trust and the persons identified as authors of
    the code. All rights reserved.  License 'Simplified BSD', as specified
    in http://opensource.org/licenses/BSD-3-Clause.

EOF

}

function die() {
    echo -e "\n$program: error: $*" >&2
    exit 1
}

function version() {
    echo -e "$program $version"
}

trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR


# Options
shortopts=hm:Mp:r:t:V
longopts=help,mysqldata=,no-mysqldir,port=,docker-repo=,tag=,version

# Default values
MYSQLDIR=$parent/data/mysql
PORT=8000
REPO="ietf/datatracker-environment"

if   [ "$(uname)" = "Linux" ]; then
    args=$(getopt -o "$shortopts" --long "$longopts" -n '$program' -- $SV "$@")
    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
    eval set -- "$args"
    sed="sed -r"
else
    # Darwin, BSDs
    args=$(getopt -o$shortopts $SV $*)
    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
    set -- $args
    sed="sed -E"
fi

while true ; do
    case "$1" in
    -h| --help) usage; exit;;       # Show this help, then exit
    -m| --mysqldir) MYSQLDIR=$2; shift;;    # Set the desired location of MySQL's database files
    -p| --port) PORT=$2; shift;;    # Bind the container's port 8000 to external port PORT
    -r| --docker-repo)  REPO=$2; shift;;    # Use the given docker repository, instead of the default
    -t| --tag)  TAG=$2; shift;;     # Use this docker image tag
    -V| --version)  version; exit;;     # Show program version, then exit
    --)     shift; break;;
    *) die "Internal error, inconsistent option specification: '$1'";;
    esac
    shift
done

if [ -z "$TAG" ]; then
    TAG=$(basename $(svn info $parent | grep ^URL | awk '{print $2}'))
fi

echo "Starting a docker container for '$REPO:$TAG'."
echo -e "\nThe web interface for 'runserver' should appear on 127.0.0.1:$PORT\n"

docker run -ti -p "$PORT:8000" \
  -v "$MYSQLDIR:/var/lib/mysql:cached" \
  -v "$parent:/root:cached" \
  "$REPO:$TAG" "$@"