# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0049_auto_20170508_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideMeetingSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.Session')),
                ('requested_prim_start_time', models.DateTimeField()),
                ('requested_alt_start_time', models.DateTimeField()),
                ('attendance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
            bases=('meeting.session',),
        ),
    ]
