# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0015_clean_primary'),
        ('meeting', '0049_auto_20170508_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideMeetingSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.Session')),
                ('requested_prim_start_time', models.DateTimeField()),
                ('requested_alt_start_time', models.DateTimeField()),
                ('contact_name', models.CharField(blank=True, default='', max_length=256)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
                ('notified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='person.Person')),
                ('notified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_by', to='person.Person')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
            bases=('meeting.session',),
        ),
        migrations.CreateModel(
            name='SideMeetingSessionTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sidemeetingsession',
            name='sidemeeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidemeeting.SideMeetingSessionTypeName'),
        ),
    ]
