# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('name', '0018_iab_programs'),
        ('meeting', '0049_auto_20170508_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtgname', models.CharField(default='', max_length=64, unique=True)),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('email', models.EmailField(default='dummy@amsl.com', max_length=254)),
                ('phone', models.CharField(max_length=256)),
                ('mtgdate', models.DateField(default=django.utils.timezone.now)),
                ('altmtgdate', models.DateField(default=django.utils.timezone.now)),
                ('days', models.IntegerField(default=1)),
                ('addcontact', models.CharField(default='', max_length=256)),
                ('addemail', models.EmailField(default='', max_length=254)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('mtgstart', models.DateTimeField(default=django.utils.timezone.now)),
                ('mtgend', models.DateTimeField(default=django.utils.timezone.now)),
                ('roomconfig', models.CharField(default='', max_length=256)),
                ('speakerphone', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('comments', models.TextField(default='')),
                ('mtg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
                ('mtgtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name.MeetingTypeName')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
