# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0049_auto_20170508_0638'),
        ('name', '0018_iab_programs'),
        ('sidemeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemeeting',
            name='addcontact',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='addemail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='addphone',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='altmtgdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='email',
            field=models.EmailField(default='dummy@amsl.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='mtg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='mtgdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='mtgend',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='mtgstart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='mtgtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='name.MeetingTypeName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='phone',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='roomconfig',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sidemeeting',
            name='speakerphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sidemeeting',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
