# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidemeeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideMeetingType',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('used', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('test', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sidemeetingsession',
            name='sidemeeting_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sidemeeting.SideMeetingType'),
            preserve_default=False,
        ),
    ]
