# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidemeeting', '0002_auto_20170516_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SideMeetingType',
            new_name='SideMeetingTypeName',
        ),
    ]
