# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20170301_0332'),
        ('sidemeeting', '0003_auto_20170517_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemeetingsession',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
            preserve_default=False,
        ),
    ]
