# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidemeeting', '0006_auto_20170524_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidemeetingsession',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sidemeetingsession',
            name='attendance',
        ),
    ]
