# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidemeeting', '0007_auto_20170524_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidemeetingsession',
            old_name='requested_alt_start_time',
            new_name='requested_alt_start_date',
        ),
        migrations.RenameField(
            model_name='sidemeetingsession',
            old_name='requested_prim_start_time',
            new_name='requested_prim_start_date',
        ),
        migrations.AddField(
            model_name='sidemeetingsession',
            name='requested_start_time',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
