#!/bin/sh
##########
#Ftp dir Optimus
/usr/bin/rsync -v \
        --rsh "/usr/local/bin/ssh" \
        --archive --update --delete \
        --links \
        --safe-links --stats \
        --exclude bin/ --exclude dev/ --exclude lib/ --exclude etc/ \
        --exclude stanfiles/ --exclude usr/ --exclude "lost+found/" \
        /ftp/ Isync@thor.cnri.reston.va.us:/usr/crap/Isync/ftp/ 

##########
#Web docs Optimus
/usr/bin/rsync -v \
        --rsh "/usr/local/bin/ssh" \
        --archive --update --delete \
        --links \
        --safe-links --stats\
        --exclude Admin/ --exclude WebSoft/ --exclude mail-archive/  \
        --exclude rfc/ \
        --exclude IESG/internal/ \
        /usr/local/apache2/htdocs/ \
        Isync@thor.cnri.reston.va.us:/usr/crap/Isync/usr/local/apache2/htdocs/ 

##########
#IESG Optimus
/usr/bin/rsync -v \
        --rsh "/usr/local/bin/ssh" \
        --archive --update --delete --links --copy-links --stats\
        --exclude Admin/ --exclude WebSoft/ --exclude mail-archive/  \
        --exclude rfc/ \
        /usr/local/apache2/htdocs/IESG/internal/ \
        Isync@thor.cnri.reston.va.us:/usr/crap/Isync/usr/local/apache2/htdocs/IESG/internal/ 

###########
#IESG Evaluations
/usr/bin/rsync -v \
        --rsh "/usr/local/bin/ssh" \
        --archive --update --delete --links --copy-links --stats\
        /usr/local/apace2/htdocs/IESG/EVALUATIONS/ \
        Isync@thor.cnri.reston.va.us:/usr/crap/Isync/usr/local/apache2/htdocs/IESG/EVALUATIONS/

