#!/usr/bin/perl

use DBI;
use Time::ParseDate;
use Time::CTime;

my $dsn = 'DBI:mysql:rt3:localhost';
my $db_user_name = 'rt_user';
my $db_password = 'rt_pass';
my ($id, $password);
my $dbh = DBI->connect($dsn, $db_user_name, $db_password);
my %alltotal;
my %allqueue;

$tmpfile="/tmp/report";
$lastweek=`date --date='6 days ago' '+%Y-%m-%d'`;
$thisweek=`date '+%Y-%m-%d'`;
# $lastweek=`date --date='8 days ago' '+%Y-%m-%d'`;
# $thisweek=`date --date='1 day ago' '+%Y-%m-%d'`;
chop $thisweek; chop $lastweek;
$etime=parsedate($thisweek);

print "Report for $lastweek to $thisweek [wish-list not included]\n";

my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Users u
	WHERE  t.Owner = u.id AND ( t.Status='new' )
	GROUP by t.Owner
});
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
	if ( $total == "" ){
    $alltotal{$username}[0]=0;
	}else{
    $alltotal{$username}[0]=$total;
	}
}
$sth->finish();

#
# do new this week
#
#    SELECT u.Name, count(*) FROM Tickets t, Queues q, Users u WHERE  t.Owner = u.id AND t.Queue = q.id AND ( t.Status='open' ) GROUP by t.Owner
#
# note queue = 22 is wish-list
#
my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Users u WHERE t.Owner = u.id AND ( t.Status='open' ) AND t.Queue != 22 GROUP by t.Owner
#    SELECT u.Name, count(*) FROM Tickets t, Users u WHERE t.Owner = u.id AND ( t.Status='open' ) GROUP by t.Owner
    });
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
	if ( $total == "" ){
     $alltotal{$username}[1]=0;
	}else{
     $alltotal{$username}[1]=$total;
	}
 }
$sth->finish();

#    SELECT u.Name, count(*) FROM Tickets t, Queues q, Users u WHERE  t.Owner = u.id AND t.Queue = q.id AND ( t.Status='resolved' OR t.Status='deleted' ) AND DATE_SUB(t.Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' GROUP by t.Owner
#

my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Users u WHERE  t.Owner = u.id AND ( t.Status='resolved' OR t.Status='deleted' ) AND DATE_SUB(t.Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND t.Queue != 22 GROUP by t.Owner
    });
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
	if ( $total == "" ){
     		$alltotal{$username}[2]=0;
	}else{
	     $alltotal{$username}[2]=$total;
	}
 }
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Users u WHERE  t.Owner = u.id AND ( t.Status='stalled' ) AND DATE_SUB(t.Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND t.Queue != 22 GROUP by t.Owner
    });
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
	if ( $total == "" ){
     		$alltotal{$username}[3]=0;
	}else{
	     $alltotal{$username}[3]=$total;
	}
 }
$sth->finish();

foreach my $key (sort keys %alltotal) {
    print$key,"\n";
    if ( $alltotal{$key}[0] ){
	print "\tNew    \t",$alltotal{$key}[0],"\n";
    }else{
	print "\tNew    \t",0,"\n";
    }
    if ($alltotal{$key}[1] ){
	print "\tOpen   \t",$alltotal{$key}[1],"\n";
    }else{
	print "\tOpen   \t",0,"\n";
    }
    if ($alltotal{$key}[2] ){
	print "\tResd   \t",$alltotal{$key}[2],"\n";
    }else{
	print "\tResd   \t",0,"\n";
    }
    if ($alltotal{$key}[3] ){
	print "\tStld   \t",$alltotal{$key}[3],"\n";
    }else{
	print "\tStld   \t",0,"\n";
    }
}

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND Queue != 22;
});
$sth->execute();
print "Total Incoming (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND Queue != 22;
});
$sth->execute();
print "Total Resolved (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(LastUpdated, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' and Status = 'deleted' AND Queue != 22;
});
$sth->execute();
print "Total Deleted (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets t, Queues q WHERE t.Queue = q.id AND t.Status = 'new' AND t.Queue != 22 AND q.Disabled != 1;
});
$sth->execute();
print "Total New (all)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets t, Queues q WHERE t.Queue = q.id AND t.Status = 'open' AND t.Queue != 22 AND q.Disabled != 1;
});
$sth->execute();
print "Total Open (all)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets t, Users u, Users r, Queues q WHERE 
	t.Queue = q.id AND
	t.Owner = u.id AND
	t.Creator = r.id AND
	(t.Status='open' OR t.Status='new') AND
	 t.Queue != 22 AND
	 q.Disabled != 1
});
$sth->execute();
print "Backlog=",$sth->fetchrow(),"\n";
$sth->finish();

$header="";
$mycount=1;
my $sth = $dbh->prepare(qq{
    SELECT t.id, t.Subject, u.Name, t.Created, r.name, q.Name FROM Tickets t, Users u, Users r, Queues q WHERE 
	t.Queue = q.id AND
	t.Owner = u.id AND
	t.Creator = r.id AND
	(t.Status='open' OR t.Status='new') AND
	 t.Queue != 22 AND
	 q.Disabled != 1
    });
$sth->execute();
while (my ($id,$subject, $owner, $created, $creator, $queue) = $sth->fetchrow_array()){
    $ptime= parsedate($created, FUZZY => 1);
    $fcreated = strftime("%m/%d/%Y",localtime($ptime));
#    $pcreated = ctime($ptime);
#    printf "Ticket#: $id\nSubject: $subject\nCreator: $creator\nDate Opened: $created\nDays in Queue: %d\nOwner: $owner\n",(($etime - $ptime) / 60 / 60 / 24);
    printf "$mycount,$id,\"$subject\",$creator,$fcreated,%d,$owner,$queue\n",(($etime - $ptime) / 60 / 60 / 24);
    $mycount++;
}
$sth->finish();


$dbh->disconnect();


