#!/usr/bin/perl

use DBI;

my $dsn = 'DBI:mysql:rt3:localhost';
my $db_user_name = 'rt_user';
my $db_password = 'rt_pass';
my ($id, $password);
my $dbh = DBI->connect($dsn, $db_user_name, $db_password);
my %alltotal;
my %allqueue;

$tmpfile="/tmp/report";
$lastweek=`date --date='7 days ago' '+%Y-%m-%d'`;
$thisweek=`date '+%Y-%m-%d'`;
$lastweek=`date --date='8 days ago' '+%Y-%m-%d'`;
$thisweek=`date --date='1 days ago' '+%Y-%m-%d'`;
chop $thisweek; chop $lastweek;

print "Report for $lastweek to $thisweek\n";

my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Queues q, Users u WHERE  t.Owner = u.id AND t.Queue = q.id AND ( t.Status='open' ) GROUP by t.Owner
});
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
    $alltotal{$username}[0]=$total;
}
$sth->finish();

#
# do new this week
#
my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Queues q, Users u WHERE  t.Owner = u.id AND t.Queue = q.id AND ( t.Status='new' ) GROUP by t.Owner
    });
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
     $alltotal{$username}[1]=$total;
 }
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT u.Name, count(*) FROM Tickets t, Queues q, Users u WHERE  t.Owner = u.id AND t.Queue = q.id AND ( t.Status='resolved' OR t.Status='deleted' ) AND DATE_SUB(t.Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' GROUP by t.Owner
    });
$sth->execute();
while (my ($username, $total) = $sth->fetchrow_array()){
     $alltotal{$username}[2]=$total;
 }
$sth->finish();

foreach my $key (sort keys %alltotal) {
    print$key,"\n";
    if ( $alltotal{$key}[1] ){
	print "\tNew    \t",$alltotal{$key}[1],"\n";
    }else{
	print "\tNew    \t",0,"\n";
    }
    if ($alltotal{$key}[0]){
	print "\tOpen   \t",$alltotal{$key}[0],"\n";
    }else{
	print "\tOpen   \t",0,"\n";
    }
    if ($alltotal{$key}[2]){
	print "\tResd   \t",$alltotal{$key}[2],"\n";
    }else{
	print "\tResd   \t",0,"\n";
    }
}

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\';
});
$sth->execute();
print "Total Incoming (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\';
});
$sth->execute();
print "Total Resolved (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE DATE_SUB(LastUpdated, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' and Status = 'deleted';
});
$sth->execute();
print "Total Deleted (past week)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE Status = 'new';
});
$sth->execute();
print "Total New (all)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets WHERE Status = 'open';
});
$sth->execute();
print "Total Open (all)=",$sth->fetchrow(),"\n";
$sth->finish();

$dbh->disconnect();


