#!/bin/bash
#
# Glen's script for cleaning up my server!

# Clean TMDA

for i in /home/*/.tmda /a/nobody/.tmda
do
	cat /dev/null > $i/incoming.log
done

find /tmp -depth -type f -mtime +7 -exec rm {} \;
find /tmp/* -depth -type d -exec rmdir --ignore-fail-on-non-empty {} \;
