#!/usr/bin/perl

use lib '/a/www/ietf-datatracker/release/';
use GEN_UTIL;
use GEN_DBUTIL;
use IETF;

init_database("ietf");

$current_time = time;
$offset_second = 185 * 24 * 3600;
$cutoff_time = $current_time - $offset_second;
$ID_DIR = "/a/www/ietf-ftp/internet-drafts";
$ARCHIVE_DIR = "/a/www/ietf/DRAFT_ARCHIVE";
chdir $ID_DIR;
while (<draft-*.*>) {
  my $inputfile = $_;
  my @stat = stat($inputfile);
  my $filesize = $stat[7];
  #my @temp = split '\.',$inputfile;
  #my $inputfile2=$temp[0];
  $inputfile =~ /(.*-\d\d)(\..*)/;
  my $inputfile2 = $1;
  my $ext = $2;
  $inputfile2 =~ /(.*)(-\d\d)/;
  my $filename =$1;
  my $revision = $2;
  $revision =~ s/-//g;
#print "$inputfile,$filename,$revision,$ext\n";exit;
  my ($revision_date,$expiration_date,$status_id) = db_select("select revision_date,expiration_date,status_id from internet_drafts where filename='$filename' and revision ='$revision'");
  if (my_defined($revision_date)) {
    if ($status_id == 3) {
      system "mv $inputfile $ARCHIVE_DIR/unknown_ids/." unless ($ext eq ".txt");   
    } elsif ($status_id =~ /2|4|5|6/) {
      my $expiration_second = get_time_stamp($expiration_date); 
      if ($expiration_second < $cutoff_time and $expiration_second > 0) {
        if ($filesize < 1500) { #tombstones
          system "mv $inputfile $ARCHIVE_DIR/deleted_tombstones/.";
          $revision = decrease_revision($revision);
          db_update("update internet_drafts set revision='$revision', expired_tombstone=1 where filename='$filename'");  #reverting the version after deleting tombstone
        } else { #possibly expired without tombstone
          system "mv $inputfile $ARCHIVE_DIR/expired_without_tombstone/.";
        }
      }
    }
  } else {
    system "mv $inputfile $ARCHIVE_DIR/unknown_ids/.";
  }
}

exit;

