#!/usr/bin/perl
##########################################################################
# Copyright © 2004 and 2003, Foretec Seminars, Inc.
##########################################################################

use lib '/a/www/ietf-datatracker/release';
use GEN_UTIL;
use GEN_DBUTIL;
use IETF;

die "USAGE: id_analyze.pl <Start Date> <End Date>\n\n" unless (defined($ARGV[1]));
init_database("ietf");

my $start_date = $ARGV[0];
my $end_date = $ARGV[1];
my $cut_off_date = db_select("select id_date from id_dates where id=4");
my $select_header = "select count(*) from internet_drafts";
$sqlStr = qq{$select_header
where start_date >= '$start_date'
and start_date <= '$end_date'
and revision_date is not null 
and revision_date <> '0000-00-00' 
and filename not like 'rfc%'
};
my $total_new_ID = db_select($sqlStr);
$sqlStr = qq{$select_header
where start_date >= '$start_date'
and start_date <= '$end_date'
and revision <> '00'
and revision_date <= '$end_date'
};
my $updated_new_ID = db_select($sqlStr);
$sqlStr .= "and revision <> '01'\n";
my $updated_two_new_ID = db_select($sqlStr);
$sqlStr = qq{$select_header
where revision_date >= '$start_date' and revision_date <= '$end_date'
and revision <> '00'
};
my $total_updated_ID = db_select($sqlStr);
$sqlStr = qq{$select_header
where lc_sent_date >= '$start_date' and lc_sent_date <= '$end_date'
};
my $total_last_call = db_select($sqlStr);
$sqlStr = qq{$select_header
where b_approve_date >= '$start_date' and b_approve_date <= '$end_date'
};
my $total_approved = db_select($sqlStr);

my ($ff1_date,$ff2_date,$ff3_date,$ff4_date) = db_select("select date_sub('$cut_off_date',interval 28 day), date_sub('$cut_off_date',interval 21 day),date_sub('$cut_off_date',interval 14 day),date_sub('$cut_off_date',interval 7 day)");

my $ff1_new = db_select("$select_header where start_date >= '$ff1_date' and start_date < '$ff2_date'");
my $ff2_new = db_select("$select_header where start_date >= '$ff2_date' and start_date < '$ff3_date'");
my $ff3_new = db_select("$select_header where start_date >= '$ff3_date' and start_date < '$ff4_date'");
my $ff4_new = db_select("$select_header where start_date >= '$ff4_date' and start_date < '$end_date'");
my $ff1_update = db_select("$select_header where revision_date >= '$ff1_date' and revision_date < '$ff2_date' and revision <> '00'");
my $ff2_update = db_select("$select_header where revision_date >= '$ff2_date' and revision_date < '$ff3_date' and revision <> '00'");
my $ff3_update = db_select("$select_header where revision_date >= '$ff3_date' and revision_date < '$ff4_date' and revision <> '00'");
my $ff4_update = db_select("$select_header where revision_date >= '$ff4_date' and revision_date < '$end_date' and revision <> '00'");
my $ff_new_ID = $ff1_new + $ff2_new + $ff3_new + $ff4_new;
my $ff_new_pt = ($ff_new_ID * 100) / $total_new_ID;
my $ff_update_ID = $ff1_update + $ff2_update + $ff3_update + $ff4_update;
my $ff_update_pt = ($ff_update_ID * 100) / $total_updated_ID;
$ff_new_pt = substr($ff_new_pt,0,2);
$ff_update_pt = substr($ff_update_pt,0,2);
my $ff_total = $ff_new_ID + $ff_update_ID;
my $ff_week1 = $ff1_new + $ff1_update;
my $ff_week2 = $ff2_new + $ff2_update;
my $ff_week3 = $ff3_new + $ff3_update;
my $ff_week4 = $ff4_new + $ff4_update;
my $ff_week1_pt = ($ff_week1 * 100) / $ff_total;
my $ff_week2_pt = ($ff_week2 * 100) / $ff_total;
my $ff_week3_pt = ($ff_week3 * 100) / $ff_total;
my $ff_week4_pt = ($ff_week4 * 100) / $ff_total;
$ff_week1_pt = substr($ff_week1_pt,0,2);
$ff_week2_pt = substr($ff_week2_pt,0,2);
$ff_week3_pt = substr($ff_week3_pt,0,2);
$ff_week4_pt = substr($ff_week4_pt,0,2);
my $meeting_num=db_select("select max(meeting_num) from meetings");
$meeting_num--;
my $mcity = db_select("select city from meetings where meeting_num=$meeting_num");
print qq{ IETF Activity since last IETF Meeting
--------------------

IETF Activity since last IETF Meeting ($mcity)

$total_new_ID \t New I-Ds   ($updated_new_ID of which were updated, some ($updated_two_new_ID) more than once)
$total_updated_ID \t I-Ds were updated   (Some more than once)
$total_last_call \t I-Ds Last Called
$total_approved \t I-Ds approved for publication

In the final 4 weeks before meeting

$ff_new_ID \t New I-Ds were received - $ff_new_pt\% of total newbies since last meeting
$ff_update_ID \t I-Ds were updated - $ff_update_pt\% of total updated since last meeting

\t\tWeek1\t$ff_week1\t$ff_week1_pt\%
\t\tWeek2\t$ff_week2\t$ff_week2_pt\%
\t\tWeek3\t$ff_week3\t$ff_week3_pt\%
\t\tWeek4\t$ff_week4\t$ff_week4_pt\%

The IESG Secretary.

};

exit;

