#!/usr/bin/perl -w
##########################################################################
# Copyright © 2003 and 2002, Foretec Seminars, Inc.
##########################################################################


use lib '/a/www/ietf-datatracker/release/';
use GEN_UTIL;
use GEN_DBUTIL;
use IETF;

init_database("ietf");
$gap = "&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ";
$table_header = qq{
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td>$gap</td>
<td>
};
$table_footer = "</td></tr></table>\n";

my $html_txt = qq{<html>
<TITLE>Working Groups under IESG Review</TITLE>
</HEAD>

<center><h2>Working Groups under IESG Review</H2></center>

This page summarizes the proposed working groups and working group recharter submissions currently under review by the IESG.  The category assignments are as follows:
<table border="1" cellspacing="2" cellpadding="2">
<tr>
<th>Category/Subcategory<br><br></th><th>Description<br><br></th>
</tr>
<tr>
<td>1. WG Creation 
</td>
<td>Proposed new working groups
</td>
</tr>
<tr>
<td>&nbsp; 1.1 In Internal Review
</td>
<td>
Internal review by the IAB, IESG, and the proposed WG chairs is in progress.
</td>
</tr>

<tr>
<td>&nbsp; 1.2 Proposed for IETF Review
</td>
<td>Internal review by the IAB, IESG, and the proposed WG chairs is in progress.  The WG is scheduled for an IESG telechat.
</td>
</tr>
<tr>
<td>&nbsp; 1.3 Proposed for Approval
</td>
<td>External review by the IETF and new-work is in progress.  The WG is scheduled for an IESG telechat.
</td>
</tr>
<tr>
<td>2. WG Rechartering
</td>
<td>Proposed rechartering of active working groups
</td>
</tr>
<tr>
<td>&nbsp; 2.1 In Internal Review
</td>
<td>
Internal review by the IAB, IESG, and the proposed WG chairs is in progress.
</td>
</tr>

<tr>
<td width="280">&nbsp; 2.2 Under Evaluation for IETF Review
</td>
<td>Internal review by the IAB, IESG, and the proposed WG chairs is in progress.  The WG is scheduled for an IESG telechat.
</td>
</tr>
<tr>
<td>&nbsp; 2.3 Proposed for Approval
</td>
<td>External review by the IETF and new-work was recommended and is in progress.  The WG is scheduled for an IESG telechat.
</td>
</tr>

</table>
<HR>
};

my @List = db_select_multiple("select id,pwg_status_val from pwg_cat order by id");
for $array_ref (@List) {
  my ($id,$val) = rm_tr(@$array_ref);
  my $sub_count1;
  my $sub_count2;
  my @temp_heading = split "::",$val;
  my $sub_heading1 = $temp_heading[0];
  my $sub_heading2 = $temp_heading[1];
  if ($id < 20) {
    $sub_count1 = "1.";
  } else {
    $sub_count1 = "2.";
  }
  $sub_count3 = $id % 10;
  $sub_count2 = $sub_count1 . $sub_count3;

  if ($id == 11 or $id == 21) {
    $html_txt .= "<h2>$sub_count1 $sub_heading1</h2>\n";
  }
  $html_txt .= "<br>$table_header\n<b>$sub_count2 $sub_heading2</b><br>\n";
  my $sqlStr = "select group_acronym_id,note,token_name from group_internal where pwg_cat_id = $id";
  $html_txt .= get_wg_action_text($sqlStr);
  $html_txt .= $table_footer;
}

$html_txt .= "<br><br><br><br><br>\n";
open (OUTFILE,">/a/www/ietf/IESG/internal/PWG.html");
print OUTFILE $html_txt;
close(OUTFILE);
                                                                                        
exit;


sub get_wg_action_text {
  my $sqlStr = shift;
  my $html_txt = "";
  my @List = db_select_multiple($sqlStr);
  if ($#List > -1) {
    $html_txt .= qq {$table_header
     <table><tr><th align="left">Area<th>Date Submitted<th>Acronym<th>Title<th>Token</tr>
};
    for $array_ref (@List) {
       my ($group_acronym_id,$note,$token_name) = rm_tr(@$array_ref);
       my $group_acronym = rm_tr(db_select("select acronym from acronym where acronym_id = $group_acronym_id"));
                                                                                
       my $area = uc(db_select("select a.acronym from acronym a,area_group ag where ag.group_acronym_id = $group_acronym_id and ag.area_acronym_id = a.acronym_id"));
       my $status_date = db_select("select last_modified_date from groups_ietf where group_acronym_id = $group_acronym_id");
       $status_date = convert_date($status_date,2);
       $status_date = convert_date($status_date);
       $status_date = "" unless ($status_date) ;
       my $group_name = rm_tr(db_select("select name from acronym where acronym_id = $group_acronym_id"));
       my $pTag = db_select("select person_or_org_tag from iesg_login where first_name = '$token_name'");
       $pTag = 0 unless (my_defined($pTag));
       my $email = get_email($pTag);

       $html_txt .= "<tr><td width=\"50\">$area</td><td align=\"center\">$status_date</td><td>$group_acronym</td><td><a href=\"/IESG/EVALUATIONS/${group_acronym}-charter.txt\">$group_name</a></td><td align=\"right\"><a href=\"mailto:$email\">$token_name</a></td></tr>\n";
       if (my_defined($note)) {
         $html_txt .= "<tr><td></td><td align=\"right\" valign=\"top\">Note:</td><td colspan=\"3\">$note</td></tr>";
       }
    }
    $html_txt .= "</table>\n";
    $html_txt .= $table_footer;
  } else {
    $html_txt .= "$gap $gap <i>NONE</i>\n";
  }
  return $html_txt;
}

