#!/usr/bin/perl

use lib '/a/www/ietf-datatracker/release';
use GEN_UTIL;
use GEN_DBUTIL_NEW;
use IETF;
init_database("ietf");
$dbh=get_dbh();
$OUTDIR="/a/www/ietf-ftp/iesg";
my @List=db_select_multiple($dbh,"select id,telechat_date,telechat_minute from telechat_minutes where exported=0 order by telechat_date");
for my $array_ref (@List) {
  my ($id,$telechat_date,$telechat_minute) = @$array_ref;
  open OUT,">$OUTDIR/iesg.$telechat_date";
  print OUT $telechat_minute;
  close OUT;
  chmod 0644, "$OUTDIR/iesg.$telechat_date";
  db_update($dbh,"update telechat_minutes set exported=1 where id=$id");
}

$dbh->disconnect();
exit
