#!/usr/bin/perl

use DBI;
use Time::ParseDate;
use Time::CTime;

my $dsn = 'DBI:mysql:rt3:localhost';
my $db_user_name = 'rt_user';
my $db_password = 'rt_pass';
my ($id, $password);
my $dbh = DBI->connect($dsn, $db_user_name, $db_password);
my %alltotal;
my %allqueue;

$tmpfile="/tmp/report";
$lastweek=`date --date='01/01/2006' '+%Y-%m-%d'`;
$thisweek=`date --date='01/01/2007' '+%Y-%m-%d'`;
chop $thisweek; chop $lastweek;
$etime=parsedate($thisweek);

print "Report for $lastweek to $thisweek [wish-list not included]\n";

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
		DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND Queue != 22;
});
$sth->execute();
print "Total Incoming =",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
		DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\'
});
$sth->execute();
print "Total Incoming (with wishlist) =",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
	DATE_SUB(Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND Queue != 22;
});
$sth->execute();
print "Total Resolved =",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
	DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND
	DATE_SUB(Resolved, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND Queue != 22;
});
$sth->execute();
print "Total Resolved (from tickets created this year)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE 
	DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND
	DATE_SUB(LastUpdated, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND
	Status = 'deleted' AND Queue != 22;
});
$sth->execute();
print "Total Deleted (from tickets created this year)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
	 (Status = 'new' or Status = 'open') AND
	 Queue != 22;
});
$sth->execute();
print "Total New/Open=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
	DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND
	 (Status = 'new' or Status = 'open') AND
	 Queue != 22;
});
$sth->execute();
print "Total New/Open(from tickets created this year)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
	 (Status = 'new' or Status = 'open') AND
	 Queue = 22;
});
$sth->execute();
print "Total New/Open (WishList)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets
	WHERE
         DATE_SUB(Created, INTERVAL 8 HOUR) BETWEEN \'$lastweek\' AND \'$thisweek\' AND
	 (Status = 'new' or Status = 'open') AND
	 Queue = 22;
});
$sth->execute();
print "Total New/Open (WishList) (from tickets created this year)=",$sth->fetchrow(),"\n";
$sth->finish();

my $sth = $dbh->prepare(qq{
    SELECT count(*) FROM Tickets t, Users u, Users r, Queues q WHERE 
	t.Queue = q.id AND
	t.Owner = u.id AND
	t.Creator = r.id AND
	(t.Status='open' OR t.Status='new') AND
	 t.Queue != 22 AND
	 q.Disabled != 1
});
$sth->execute();
# print "Backlog=",$sth->fetchrow(),"\n";
$sth->finish();

$dbh->disconnect();


