#!/bin/sh
pcount=`ps -ef | grep postconfirmd | grep -v grep | wc -l`
if [ $pcount -gt 0 ]
then
	exit 0
fi
/etc/init.d/postconfirmd stop 2>/dev/null
sleep 2
/etc/init.d/postconfirmd start 2>/dev/null
date | mail -s PostconfirmdRestartd glen@amsl.com henrik@levkowetz.com
exit 0
