#!/bin/sh
pcount=`ps -ef | grep amavis | grep -v grep | wc -l`
if [ $pcount -gt 1 ]
then
	exit 0
fi
rcamavis stop
sleep 2
rm -f /a/amavis/amavisd.lock /a/amavis/amavisd.pid /a/amavis/amavisd.sock
sleep 2
rcamavis start
date | mail -s AmavisRestartd glen@amsl.com
exit 0
