#!/bin/sh
pcount=`ps -ef | grep proftp | grep -v grep | wc -l`
if [ $pcount -gt 0 ]
then
	exit 0
fi
/etc/init.d/proftpd stop
sleep 2
/etc/init.d/proftpd start
date | mail -s ProftpdRestartd glen@amsl.com
exit 0
