#!/usr/bin/perl
##########################################################################
# Copyright © 2004 and 2003, Foretec Seminars, Inc.
##########################################################################

use lib '/a/www/ietf-datatracker/release';
use GEN_DBUTIL;
use GEN_UTIL;
use IETF;

init_database("ietf");
$current_date = db_select("select current_date");
my $second_cut_off_days = db_select("select to_days(id_date) from id_dates where id=2");
my $ietf_monday_days = db_select("select to_days(id_date) from id_dates where id=3");
my $c_days = db_select("select to_days('$current_date')");
my $c_hour = db_select("select hour(current_time)");
if ($c_days >= $second_cut_off_days and $c_days < $ietf_monday_days) { 
  if ($c_days == $second_cut_off_days and $c_hour < 9) {
    last;
  } else {
    exit;
  }
}
my $set = "";
my @to_be_noticed = ();
my $tracker_set = "";
my @List = db_select_multiple("select id_document_tag from id_internal where cur_state < 42");
for $array_ref (@List) {
  my ($id_document_tag) = @$array_ref;
  $tracker_set .= "$id_document_tag,";
}
chop($tracker_set);
#where revision_date < date_add(date_sub((date_sub(current_date,interval 185 day)), interval dayofmonth(date_sub(current_date,interval 185 day)) day), interval 1 day)
my $sqlStr = qq{
select id_document_tag from internet_drafts
where revision_date < date_add(date_sub(current_date,interval 185 day),interval 1 day)
and  status_id = 1 
and id_document_tag not in ($tracker_set)
and review_by_rfc_editor = 0
};
my @List2 = db_select_multiple($sqlStr);
for $array_ref (@List2) {
  my ($id_document_tag) = @$array_ref;
  $set .= "$id_document_tag,";
  push @to_be_noticed, $id_document_tag;
}
chop($set);
exit unless (my_defined($set));
$sqlStr = qq{
update internet_drafts
set dunn_sent_date=date_sub(current_date, interval 1 day)
where id_document_tag in ($set)
};
#die "$sqlStr\n";
db_update($sqlStr);
my $subject="I-D was expired";
my $from="I-D Expiring System <ietf-secretariat-reply\@ietf.org>";
for my $array_ref (@to_be_noticed) {
  my ($filename,$revision) = db_select("select filename,revision from internet_drafts where id_document_tag=$array_ref");
  my $ad_id = db_select("select person_or_org_tag from iesg_login a, id_internal b where id_document_tag=$array_ref and b.job_owner=a.id");
  my $cur_state = db_select("select cur_state from id_internal where id_document_tag=$array_ref");
  my $state_name = ($cur_state == 99)?"Dead":"Ad is watching";
  my $name = get_name($ad_id);
  my $email =get_email($ad_id);
  my $to = "$name <$email>";
  my $mail_body = qq{$filename-$revision.txt was just expired.
This I-D is in '$state_name' state in ID Tracker.

Thanks,
IETF Secretariat.

};
#   open MAIL, "| /usr/lib/sendmail -t -i";
#   print MAIL <<END_OF_MESSAGE;
#From: $from
#To: $to
#Subject:$subject
                                                                                                     
#$mail_body
#END_OF_MESSAGE
#   close MAIL;
   send_mail("set_dunn_date.pl","ietf",$email,$from,$subject,$mail_body);
}
exit;


