#!/bin/bash
#
# A cron job that takes the mail and adds it
# to the mhonarc archives for the working groups
#
# set this to the root of where the archives should be stored

global_lock()
{
    while [ -f "$LOCKFILE" ] ; do
	echo $0: sleep for lock
	sleep 5;
    done
    touch "$LOCKFILE"
}

global_unlock()
{
    if [ ! -f "$LOCKFILE" ] ; then
	echo $0: lockfile missing $LOCKFILE
    else
	rm "$LOCKFILE"
    fi
}

LIST=$1
LOCKFILE=/a/www/ietf-mail-archive/${LIST}-temp.message
ARCHIVE_ROOT_DIR=/a/www/ietf-mail-archive/web
LIST_ARCHIVE_DIR=$ARCHIVE_ROOT_DIR/$LIST
LIST_ARCHIVE_RCFILE=$LIST_ARCHIVE_DIR/mhonarc.rcfile
MAIL_ARCHIVE_FILE=$LIST_ARCHIVE_DIR/current.mail
MAIL_ARCHIVE_FILE_TEMP=$LIST_ARCHIVE_DIR/current.mail.temp
ERROR_FLAG=0

cd $ARCHIVE_ROOT_DIR

if [ ! -f $LIST_ARCHIVE_RCFILE ] || [ ! -f $MAIL_ARCHIVE_FILE ] ; then
    echo "$0: no rcfile or current.mail for list $LIST"
    exit 1
fi

if [ ! -s $MAIL_ARCHIVE_FILE ]; then
echo empty $MAIL_ARCHIVE_FILE skipping
exit 0
fi

global_lock
if [ -f $MAIL_ARCHIVE_FILE_TEMP ]; then
echo $MAIL_ARCHIVE_FILE_TEMP exists
exit 1
fi
mv $MAIL_ARCHIVE_FILE $MAIL_ARCHIVE_FILE_TEMP
global_unlock

mhonarc -umask 000 -add -outdir $LIST_ARCHIVE_DIR/current -definevar list-name=$LIST -rcfile $LIST_ARCHIVE_RCFILE $MAIL_ARCHIVE_FILE_TEMP

cp $LIST_ARCHIVE_DIR/current/maillist.html $LIST_ARCHIVE_DIR/current/index.html

if [ -d $LIST_ARCHIVE_DIR/current/.mhonarc.lck ]; then
echo "$0: mhonarc lock file stuck in $LIST"
else
rm $MAIL_ARCHIVE_FILE_TEMP
fi

exit 0
