#!/bin/bash

cd /a/www/ietf-mail-archive/web

for i in `find . -maxdepth 2 -name current.mail -print | sort`; do
    if [ -s $i ] ; then
	LIST=`echo $i | awk -F\/ '{print $2}'`
	echo "---- $LIST ---- "
	/a/ietf/scripts/mhonarc-single $LIST
	STATUS=$?
	if [ $STATUS -eq 1 ]; then
		echo "==== ERROR IN $LIST ==== "
	fi
    fi
done
