#!/usr/bin/perl

##########################################################################
# Copyright © 2004, Foretec Seminars, Inc.
##########################################################################

use lib '/a/www/ietf-datatracker/release';
use GEN_DBUTIL;
use GEN_UTIL;
use IETF;
init_database("ietf");

$program_title = "Internet-Drafts Status Summary";
$IN_TRACK = 0;
$ACTIVE=1;
$PUBLISHED=3;
$EXPIRED=2;
$WITHDRAWN_SUBMITTER=4;
$REPLACED=5;
$WITHDRAWN_IETF=6;

$in_track_ids = "";
my @List = db_select_multiple("select id_document_tag from id_internal where rfc_flag = 0 and cur_state not in (99,32,42)");
for my $array_ref (@List) {
  my ($id) = @$array_ref;
  $in_track_ids .= "$id,";
}
chop($in_track_ids);

$text_top = qq|
$program_title

Web version is available at
https://datatracker.ietf.org/public/idindex.cgi

|;

$text_body = get_text_body();

print qq{$text_top
$text_body
};

sub get_text_body {
   my $text_txt=get_list($IN_TRACK);
   $text_txt .= get_list($ACTIVE);
   $text_txt .= get_list($PUBLISHED);
   $text_txt .= get_list($EXPIRED);
   $text_txt .= get_list($WITHDRAWN_SUBMITTER);
   $text_txt .= get_list($WITHDRAWN_IETF);
   $text_txt .= get_list($REPLACED);
   return "$text_txt";
}

sub get_list {
  my $status_id=shift;
  my $ret_txt = undef;
  my $sqlStr = undef;
  unless ($status_id) {
    $sqlStr = "select id_document_tag,revision_date,status_value,filename,expired_tombstone,revision from internet_drafts a, id_status c where a.status_id=c.status_id and id_document_tag in ($in_track_ids) order by filename";
  } else {
    $sqlStr = "select id_document_tag,revision_date,status_value,filename,expired_tombstone,revision,rfc_number,replaced_by from internet_drafts a, id_status c where a.status_id=c.status_id and id_document_tag not in ($in_track_ids) and a.status_id=$status_id order by filename";
  }
  my @List = db_select_multiple($sqlStr);
  for my $array_ref (@List) {
    my ($id_document_tag,$date,$status_value,$filename,$expired_tombstone,$revision,$rfc_number,$replaced_by) = @$array_ref;
    $revision=decrease_revision($revision) if ($status_id > $ACTIVE and $expired_tombstone==0);
    unless ($status_id) {
      my $cur_state = db_select("select document_state_val from id_internal a, ref_doc_states_new b where a.id_document_tag=$id_document_tag and rfc_flag=0 and a.cur_state=b.document_state_id");
      my $sub_state = db_select("select sub_state_val from id_internal a, sub_state c where a.id_document_tag=$id_document_tag and rfc_flag=0 and a.cur_sub_state_id=c.sub_state_id");
      $cur_state .= "::$sub_state" if ($sub_state);
      $status_value = "In IESG processing - ID Tracker state <$cur_state>";
    }
    if ($status_id == $REPLACED) {
      my $filename = db_select("select filename from internet_drafts where id_document_tag=$replaced_by");
      $status_value .= " replaced by $filename";
    }
    $rfc_number = "" unless ($status_id == $PUBLISHED);
    $ret_txt.="$filename-$revision\t$date\t$status_value\t$rfc_number\n";
    
  }
  return $ret_txt;
}


