#!/usr/bin/perl
##########################################################################
# Copyright © 2003 and 2004, Foretec Seminars, Inc.
##########################################################################

use lib '/a/www/ietf-datatracker/release';
use GEN_UTIL;
use GEN_DBUTIL;
use IETF;

init_database("ietf");

$test_mode = 0;
$X_heading = "";

my $test_url = "";
my $c_time = get_current_time();
my $c_date = get_current_date();
print "[$c_time, $c_date]\n\n";
my $sqlStr = qq{select b.id_document_tag,b.job_owner, b.ballot_id, 
a.filename, c.ballot_writeup,b.cur_state, b.cur_sub_state_id,a.revision,
b.rfc_flag from internet_drafts a, 
id_internal b left outer join ballot_info c on b.ballot_id = c.ballot_id
where a.id_document_tag = b.id_document_tag
and lc_expiration_date <= current_date
and cur_state = 16
};
my @List = db_select_multiple($sqlStr);
for $array_ref (@List) {
  my ($id_document_tag,$ad_id,$ballot_id,$filename,$ballot_writeup,$old_state,$old_sub_state_id,$revision,$rfc_flag) = rm_tr(@$array_ref);
  $filename = "RFC $id_document_tag" if ($rfc_flag);
  my $msg_txt = "IETF Last Call has ended, and the state has been changed to ";
  my $new_state = 19;
  unless (my_defined($ballot_writeup)) {
    $new_state = 18;
    
  }
  $new_state = 18 if ($ballot_writeup =~ /What does this protocol do and why/);
  my $new_state_name = rm_tr(db_select("select document_state_val from ref_doc_states_new where document_state_id=$new_state"));
  my $old_state_name = rm_tr(db_select("select document_state_val from ref_doc_states_new where document_state_id = $old_state"));
  $old_state_name = "$old_state_name::" . rm_tr(db_select("select sub_state_val from sub_state where sub_state_id=$old_sub_state_id")) if ($old_sub_state_id > 0);
  $msg_txt .= $new_state_name;
  $msg_txt .="\n\nhttps://datatracker.ietf.org/cgi-bin/${test_url}idtracker.cgi?command=view_id&dTag=$id_document_tag&rfc_flag=$rfc_flag&ballot_id=$ballot_id\n";
  $sqlStr = qq{update id_internal
set cur_state = $new_state,cur_sub_state_id = 0,
prev_state=$old_state,prev_sub_state_id=$old_sub_state_id,
event_date = current_date where ballot_id = $ballot_id
};
  unless (db_update($sqlStr)) {
    print "Processing $filename failed\n";
    next;
  }
  unless (email_to_AD($filename,$msg_txt,$ad_id)) {
    print "$filename has processed, but sending notification to AD has failed\n";
    next;
  }
  $revision = db_quote($revision);
  my $comment_txt = db_quote("State has been changed to <b>$new_state_name</b> from <b>$old_state_name</b> by system");
  $sqlStr = qq{insert into document_comments
(document_id,public_flag,comment_date,comment_time,comment_text,result_state,origin_state,version) values ($id_document_tag,1,current_date,current_time,$comment_txt,$new_state,$old_state,$revision)
};
  unless (db_update($sqlStr)) {
    print "$filename has been processed and notification has been sent out, but recording comment has failed\n";
    next;
  }
  print "$filename has been processed,  notification has been sent out, and recording comment was successful\n";

}  #End of For Loop
print "\n\n";
exit;

sub email_to_AD {
   my ($filename,$msg_txt,$ad_id) = @_;
#   my $sqlStr = qq{
#   select email_address from email_addresses e,iesg_login i
#   where i.id = $ad_id
#   AND i.person_or_org_tag = e.person_or_org_tag
#   AND e.email_priority = 1
#   };
#   my $email_address = rm_tr(db_select($sqlStr));
   my $email_address = "iesg\@ietf.org";
   #$email_address = "mlee\@foretec.com";
   if ($test_mode) {
     open MAIL, "| /usr/lib/sendmail $TEST_EMAIL" or return 0;
   } else {
     open MAIL, "| /usr/lib/sendmail  $email_address" or return 0;
   }
   print MAIL <<END_OF_MESSAGE;
To: $email_address
Cc: iesg-secretary\@ietf.org 
From: "DraftTracker Mail System" <iesg-secretary\@ietf.org>
Subject: Last Call Expired: <$filename> 
$X_heading

Please DO NOT reply on this email.
                                                                                      
ID: $filename

$msg_txt

END_OF_MESSAGE
                                                                                      
   close MAIL or return 0;
   return 1;
                                                                                      
}

