insert into from_bodies (from_id, body_name) values (135,"ITU-T SG 15, Q.14/15");
insert into from_bodies (from_id, body_name) values (136,"ATM Forum AIC WG");
insert into from_bodies (from_id, body_name) values (137,"MPLS and FR Alliance");
insert into from_bodies (from_id, body_name) values (138,"ISO/IEC JTC 1 SC 29/WG 11");
insert into from_bodies (from_id, body_name) values (139,"ITU-T SG 15 WP 1");
insert into from_bodies (from_id, body_name) values (140,"IETF Transport Area");
insert into from_bodies (from_id, body_name) values (141,"T1S1");
insert into from_bodies (from_id, body_name) values (142,"ITU-T Q.5/13");
insert into from_bodies (from_id, body_name) values (143,"IETF DISMAN WG");
insert into from_bodies (from_id, body_name) values (144,"ITU-T SG 15 Q14/15");
insert into from_bodies (from_id, body_name) values (145,"IETF ENUM WG");
insert into from_bodies (from_id, body_name) values (146,"IETF Mobile IP WG");
insert into from_bodies (from_id, body_name) values (147,"ITUT-T SG 16");
insert into from_bodies (from_id, body_name) values (148,"T1M1");
insert into from_bodies (from_id, body_name) values (149,"Sigtran WG");
insert into from_bodies (from_id, body_name) values (150,"T1X1 cc: ITU-T Q. 14/15 (for information)");
insert into from_bodies (from_id, body_name) values (151,"MPLS Forum");
insert into from_bodies (from_id, body_name) values (152,"IETF SUB-IP Area");
insert into from_bodies (from_id, body_name) values (153,"AVT WG");
insert into from_bodies (from_id, body_name) values (154,"SIP, SIPPING, SIMPLE WGs");
insert into from_bodies (from_id, body_name) values (155,"WIG");
insert into from_bodies (from_id, body_name) values (156,"SC 29/WG 11");
insert into from_bodies (from_id, body_name) values (157,"SC 29/WG 1");
insert into from_bodies (from_id, body_name) values (158,"ISO/IEC JTC SC 29/WG11");
insert into from_bodies (from_id, body_name) values (159,"IETF Sub-IP Area");
insert into from_bodies (from_id, body_name) values (160,"ISO/IEC JTC SC 29/WG1");
insert into from_bodies (from_id, body_name) values (161,"ITU-Q.14/15");
insert into from_bodies (from_id, body_name) values (162,"ITU-T SG 15, Q.11");
insert into from_bodies (from_id, body_name) values (163,"ITU-SC29");
insert into from_bodies (from_id, body_name) values (164,"SC29 4559");
insert into from_bodies (from_id, body_name) values (165,"SC29 4561");
insert into from_bodies (from_id, body_name) values (166,"Sigtran");
insert into from_bodies (from_id, body_name) values (167,"ITU-T SG 7");
insert into from_bodies (from_id, body_name) values (168,"ITU-SG 15");
insert into from_bodies (from_id, body_name) values (169,"ISO/IEC JTC1/SC29/WG11");
insert into from_bodies (from_id, body_name) values (170,"ITU-SG 7");
insert into from_bodies (from_id, body_name) values (171,"ITU-SG 8");
insert into from_bodies (from_id, body_name) values (172,"ISO/IEC JTC1/SC6");
insert into uploads (file_id,file_title,file_extension,detail_id) values (755,' Liaison Statement To IETF CCAMP WG on draft-ietf-ccamp-gmpls-ason-reqts',".html",635);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (635,"2004-02-01",135,"IETF CCAMP WG Chairs",1,NULL,"IETF CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (756,' Response to IETF CCAMP WG regarding Comments on G.7713.2',".html",636);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (636,"2004-02-01",73,"IETF CCAMP",1,NULL,"IETF CCAMP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (757,' Response To IETF CCAMP WG on ASON Routing Requirements',".html",637);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (637,"2004-02-01",135,"IETF CCAMP WG Chairs",1,NULL,"IETF CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (758,' Information on L1VPN related work in SG 13',".pdf",638);
insert into uploads (file_id,file_title,file_extension,detail_id) values (759,' Questionnaire in the area of Layer 1 VPN series',".pdf",638);
insert into uploads (file_id,file_title,file_extension,detail_id) values (760,' Document summerizing Layer ! VPN work in SG 13 up to now',".pdf",638);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (638,"2004-02-01",113,"IETF Routing Area (CCAMP WG) and Internet Area (L2VPN WG and L3VPN WG)",1,NULL,"IETF Routing Area (CCAMP WG) and Internet Area (L2VPN WG and L3VPN WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (761,' L2VPN over MPLS solution space',".pdf",639);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (639,"2004-02-01",113,"IETF Internet Area (L2VPN WG)",1,NULL,"IETF Internet Area (L2VPN WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (762,' TDM-MPLS network interworking',".pdf",640);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (640,"2004-02-01",113,"IETF PWE3 WG",1,NULL,"IETF PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (763,' Reply to the Liaison on Structured Probable Cause',".pdf",641);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (641,"2004-02-01",113,"IETF DISMAN WG",1,NULL,"IETF DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (764,' Liaison Statement on NGN Studies',".pdf",642);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (642,"2004-02-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (765,' Liaison Statement to ITU-T SGs, ITU-R WGs, IETF on the ITU-T IP Project',".pdf",643);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (643,"2004-02-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (766,' Laiason from ATM Forum to PWE3 Working Group',".txt",644);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (644,"2004-02-01",136,"PWE3 Working Greoup Chairs",1,NULL,"PWE3 Working Greoup Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (767,' MINUTES: IETF/W3C coordination call',".txt",645);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (645,"2004-02-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (768,' Liaison from MPLS and Frame Relay Alliance to PWE3 WG',".txt",646);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (646,"2004-01-01",137,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (769,' Liaison Statement from SC 29/WG 11 to All Liaison Organizations on Progress of MPEG Standards',".htm",647);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (647,"2003-12-01",138,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (770,' Liaison Response from the IETF CCAMP WG to ITU-T SG 15, Q.14/15 Regarding ASON',".html",648);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (648,"2003-12-01",27,"ITU-T SG 15, Q.14/15",1,NULL,"ITU-T SG 15, Q.14/15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (771,' Liaison Statement to IETF regarding translation of IETF xDSL MIBs for use with OMCI',".html",649);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (649,"2003-12-01",139,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (772,' Liaison Statement To IETF Transport Area on Change Procedures for RSVP ',".html",650);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (650,"2003-12-01",73,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (773,' Liaison statement to IETF regarding translation of IETF xDSL MIBs for use with OMCI',".html",651);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (651,"2003-12-01",73,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (774,' Liaison Response Regarding Liaison Statement on RSVP Change Process',".txt",652);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (652,"2003-12-01",73,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (775,' Liaison Statement on RSVP Change Process',".txt",653);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (653,"2003-12-01",140,"ITU-T SG 15",1,NULL,"ITU-T SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (776,' Announcement of Consent for Q.811 and Q.812 (LOWER/UPPER LAYER PROTOCOL PROFILES FOR THE Q AND X INTERFACE)',".html",654);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (654,"2003-11-01",66,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (777,' Structured Probable Cause',".html",655);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (655,"2003-11-01",66,"IETF DISMAN WG",1,NULL,"IETF DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (778,' T1S1 requirements for a solution to DTMF Digit Collection',".pdf",656);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (656,"2003-11-01",141,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (779,' TDM - MPLS network internetworking',".htm",657);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (657,"2003-11-01",142,"IETF PWE3 WG",1,NULL,"IETF PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (780,' Re: draft-ietf-aaa-diameter-nasreq-13a.txt',".pdf",658);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (658,"2003-11-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (781,' Re: DMU (Dynamic Mobile-IP Key Update',".pdf",659);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (659,"2003-11-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (782,'Response to Liaison on Alarm MIB ',".txt",660);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (660,"2003-10-01",143,"ITU-T SG 4",1,NULL,"ITU-T SG 4");
insert into uploads (file_id,file_title,file_extension,detail_id) values (783,' Liaison Statement from the ATM Forum to the IETF PWE3',".html",661);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (661,"2003-10-01",4,"IETF PWE3",1,NULL,"IETF PWE3");
insert into uploads (file_id,file_title,file_extension,detail_id) values (784,' ASON Status',".html",662);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (662,"2003-10-01",73,"IETF CCAMP WG and Routing Area Directors",1,NULL,"IETF CCAMP WG and Routing Area Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (785,' Liaison Statement to IETF CCAMP on RSVP-TE and CR-LDP',".html",663);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (663,"2003-10-01",73,"IETF CCAMP",1,NULL,"IETF CCAMP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (786,' Liaison Statement - Optical Transport Networks &amp; Technologies Standardization Work Plan, Issue 4',".html",664);
insert into uploads (file_id,file_title,file_extension,detail_id) values (787,'Attachement - Optical Transport Networks &amp; Technologies Standardization Work Plan, Issue 4 ',".html",664);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (664,"2003-10-01",73,"IETF (Sub-IP &amp; Transport Areas)",1,NULL,"IETF (Sub-IP &amp; Transport Areas)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (788,' Liaison Statement: Proposal for Signalling Security Requirements at PSTN Interconnection with VoIP networks',".pdf",665);
insert into uploads (file_id,file_title,file_extension,detail_id) values (789,' Delayed Contribution 101: Proposal for Signalling Security Requirements at PSTN Interconnection with VoIP networks',".pdf",665);
insert into uploads (file_id,file_title,file_extension,detail_id) values (790,' Draft ITU-T Recommendation X.805 (Formerly X.css), Security architecture for systems providing end-to-end communications',".pdf",665);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (665,"2003-09-01",75,"ITU-T SG 4, 9, 11, 13, 16 and IETF",1,NULL,"ITU-T SG 4, 9, 11, 13, 16 and IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (791,' Frame relay services over MPLS core networks',".pdf",666);
insert into uploads (file_id,file_title,file_extension,detail_id) values (792,' Draft new recommendation X.84 - support frame relay services over MPLS core networks',".pdf",666);
insert into uploads (file_id,file_title,file_extension,detail_id) values (793,' Working text for a proposed amendment to draft new recommendation X.84',".pdf",666);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (666,"2003-09-01",75,"IETF PWE3 Working Group",1,NULL,"IETF PWE3 Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (794,' MPLS Signalling Protocols',".pdf",667);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (667,"2003-08-01",113,"IETF Sub IP Area",1,NULL,"IETF Sub IP Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (795,' The Liaison Statement to on the ITU-T IP Project',".pdf",668);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (668,"2003-08-01",113,"ITU-T SGs, ITU-R WGs, ITU-D SG2 and the IETF",1,NULL,"ITU-T SGs, ITU-R WGs, ITU-D SG2 and the IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (796,' Communication of Y.MPLSperf (file #2)',".pdf",669);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (669,"2003-08-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (797,' Communication of Y.MPLSperf',".pdf",670);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (670,"2003-08-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (798,' ATM and TDM-MPLS network interworking- user plane interworking',".pdf",671);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (671,"2003-08-01",113,"IETF (PWE3 WG)",1,NULL,"IETF (PWE3 WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (799,' ATM Forum Liaison Statement',".txt",672);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (672,"2003-07-01",4,"IETF-PWE3",1,NULL,"IETF-PWE3");
insert into uploads (file_id,file_title,file_extension,detail_id) values (800,' Address Space Relationships in ASON',".htm",673);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (673,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (801,' Proposed Template for Assessment of Specific Protocols Against ITU-T G.8080 and G.7715 Recommendations',".htm",674);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (674,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (802,' Draft G. 7715.1 (Attachment for Liaison Statement to IETF on definition of ASON Routing Requirements)',".htm",675);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (675,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (803,' Liaison Statement to IETF on definition of ASON Routing Requirements',".htm",676);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (676,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (804,'Liaison Statement To IETF on ASON Signaling Protocol Extensions',".pdf",677);
insert into uploads (file_id,file_title,file_extension,detail_id) values (805,'Liaison Statement To IETF on ASON Signaling Protocol Extensions updated Living List',".pdf",677);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (677,"2003-06-01",144,"IETF CCAMP WG and Sub-IP Area Directors",1,NULL,"IETF CCAMP WG and Sub-IP Area Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (806,' RFC 2916 is about to be revised',".txt",678);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (678,"2003-06-01",145,"ITU-T SG 2",1,NULL,"ITU-T SG 2");
insert into uploads (file_id,file_title,file_extension,detail_id) values (807,' Security for Management Interfaces to Transport Network Elements',".pdf",679);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (679,"2003-06-01",25,"IETF Operations and Management Area",1,NULL,"IETF Operations and Management Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (808,'Minutes from the June 17, 2003 IETF/W3C teleconference',".html",680);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (680,"2003-06-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (809,' RE: Liaison statement from ITU-T Q.11/13 to IETF (mobileip, mpls WGs) on "Draft Recommendation Y.MIPoMPLS (Mobile IP Services over MPLS)" ',".txt",681);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (681,"2003-06-01",146,"ITU-T SG 13",1,NULL,"ITU-T SG 13");
insert into uploads (file_id,file_title,file_extension,detail_id) values (810,' Draft Recommendation Y.MIPoMPLS (Mobile IP Services over MPLS) for consent (Liaison Statement)',".pdf",682);
insert into uploads (file_id,file_title,file_extension,detail_id) values (811,' Draft new Recommendation Y.MIPoMPLS (Document)',".pdf",682);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (682,"2003-06-01",113,"IETF mobileip WG and mpls WG",1,NULL,"IETF mobileip WG and mpls WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (812,' LS to 3GPP, 3GPP2 and IETF on Transport Layer for MSC-VBR and EV',".pdf",683);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (683,"2003-05-01",147,"IETF avt and mmusic WG",1,NULL,"IETF avt and mmusic WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (813,' Final Report of the Workshop on Telecommunications for Disaster Relief',".pdf",684);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (684,"2003-05-01",74,"IETF ieprep WG",1,NULL,"IETF ieprep WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (814,' Avoiding Conflicts Between 3GPP2 and IETF Meetings',".pdf",685);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (685,"2003-05-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (815,' T1M1s New Primary Method of Operation and Increased Collaboration Opportunities ',".txt",686);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (686,"2003-05-01",148,"IETF O&amp;M Area",1,NULL,"IETF O&amp;M Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (816,' Sigtran WG Liaison Response: New Recommendation G.769',".txt",687);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (687,"2003-05-01",149,"ITU-T SG 15",1,NULL,"ITU-T SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (817,' Input to IETF EAP Working Group on Methods and Key Strength',".txt",688);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (688,"2003-04-01",101,"EAP Working Group",1,NULL,"EAP Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (818,' Liaison from T1X1 to IETF ccamp regarding draft-ietf-ccamp-lmp-test-sdh-02.txt',".pdf",689);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (689,"2003-04-01",150,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (819,'Minutes from the March 13, 2003 IETF/W3C teleconference',".html",690);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (690,"2003-03-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (820,' Transport of TDM over MPLS networks',".txt",691);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (691,"2003-02-01",151,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (821,' IETF decision to focus on RSVP-TE as the basis for constraint-based LSP management IETF has decided to focus on RSVP-TE as the basis for constraint-based LSP management ',".txt",692);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (692,"2003-02-01",152,"ITU-T SG 13, SG 15",1,NULL,"ITU-T SG 13, SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (822,' Framework of new Recommendation O.iptest',".htm",693);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (693,"2003-02-01",66,"Transport ADs (Allison Mankin and Scott Bradner)",1,NULL,"Transport ADs (Allison Mankin and Scott Bradner)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (823,'Use of RFC 3430',".txt",694);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (694,"2003-02-01",66,"OPS ADs (Randy Bush and Bert Wijnen)",1,NULL,"OPS ADs (Randy Bush and Bert Wijnen)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (824,' Announcement of the consent of M.3017 (Framework for the Integrated Management of Hybrid Circuit/Packet Networks)',".htm",695);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (695,"2003-02-01",66,"OPS ADs (Randy Bush and Bert Wijnen)",1,NULL,"OPS ADs (Randy Bush and Bert Wijnen)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (825,' Liaison on Alarm MIB',".txt",696);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (696,"2003-02-01",66,"DISMAN WG",1,NULL,"DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (826,' Liaison Statement To IETF CCAMP WG and Sub-IP Area Directors From WP3/15 on ASON Routing Activities',".htm",697);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (697,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (827,' Optical Transport Networks &amp; Technologies Standardization Work Plan, Issue 3',".htm",698);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (698,"2003-01-01",73,"SUB-IP and Transport Areas",1,NULL,"SUB-IP and Transport Areas");
insert into uploads (file_id,file_title,file_extension,detail_id) values (828,'Liaison Statement To IETF CCAMP WG and Sub-IP Area Directors From WP3/15 on ASON Routing Activities',".htm",699);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (699,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (829,' ASON Status and GMPLS Protocol Support for Restoration/Re-routing Capabilities',".htm",700);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (700,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (830,' Input on SDH and OTN Discovery Mechanisms',".htm",701);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (701,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (831,'Information of a new Recommendation G.769',".htm",702);
insert into uploads (file_id,file_title,file_extension,detail_id) values (832,'Attachment to above: D-711 E Transmission schemes of SS7 Signaling optimised for IP-CME',".htm",702);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (702,"2003-01-01",73,"SIGTRAN WG",1,NULL,"SIGTRAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (833,'CDMA2000 wireless IP network specification (P.S0001-C) - Baseline specifications',".html",703);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (703,"2003-01-01",104,"Various IETF WGs",1,NULL,"Various IETF WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (834,'e164.arpa domain management LIAISON STATEMENT',".txt",704);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (704,"2002-12-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (835,'Administrative aspects of ENUM - Security LIAISON STATEMENT',".txt",705);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (705,"2002-12-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (836,'Request for comments on proposed draft Amendment 1 to X.85/Z.1321, bit oriented method for LAPS as Annex D (PDF File)',".pdf",706);
insert into uploads (file_id,file_title,file_extension,detail_id) values (837,'Attachment to above (PDF File)',".pdf",706);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (706,"2002-12-01",75,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (838,'Liaison statement from IETF AVT working group to ISO/IEC/JTC1/SC29/WG11',".txt",707);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (707,"2002-12-01",153,"SC29/WG11",1,NULL,"SC29/WG11");
insert into uploads (file_id,file_title,file_extension,detail_id) values (839,'3GPP final response on IMS interoperability concerns',".htm",708);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (708,"2002-12-01",99,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (840,'Administrative aspects of ENUM - Security',".htm",709);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (709,"2002-12-01",64,"IAB/ISOC",1,NULL,"IAB/ISOC");
insert into uploads (file_id,file_title,file_extension,detail_id) values (841,'e164.arpa domain management',".htm",710);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (710,"2002-12-01",64,"ISOC/IAB Liaison",1,NULL,"ISOC/IAB Liaison");
insert into uploads (file_id,file_title,file_extension,detail_id) values (842,'Recommendation E.360 QoS routing and related traffic engineering methods for IP-, ATM- and TDM-based multiservice networks',".htm",711);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (711,"2002-12-01",64,"TEWG, MPLS, CCAMP WGs",1,NULL,"TEWG, MPLS, CCAMP WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (843,'L1 VPN service requirements and architecture',".htm",712);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (712,"2002-11-01",113,"PPVPN WG",1,NULL,"PPVPN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (844,'Liaison statement on the ITU-T IP Project ',".pdf",713);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (713,"2002-11-01",113,"IETF (and others)",1,NULL,"IETF (and others)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (845,'ATM-MPLS Network Interworking ',".pdf",714);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (714,"2002-11-01",113,"PWE WG",1,NULL,"PWE WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (846,'Minutes from the November 12, 2002 IETF/W3C teleconference',"",715);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (715,"2002-11-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (847,'ITU liaison statement',".html",716);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (716,"2002-10-01",73,"Scott Bradner",1,NULL,"Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (848,'Liaison to multiple SDOs requesting input for "Media Coding Summary Database" project',".htm",717);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (717,"2002-10-01",74,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (849,'New Question on Use of Public Telecommunication Services for Emergency and Disaster Relief Operations',".htm",718);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (718,"2002-10-01",74,"IEPREP WG",1,NULL,"IEPREP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (850,'Liaison Statement on Interoperability Issues and SIP in IMS',".txt",719);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (719,"2002-09-01",154,"3GPP",1,NULL,"3GPP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (851,'3GPP response to Liaison Statement on Interoperability Issues and SIP in IMS',".txt",720);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (720,"2002-09-01",99,"SIP, SIPPING, SIMPLE WGs",1,NULL,"SIP, SIPPING, SIMPLE WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (852,'Liaison statement about new Wireless LAN Interworking Group (WIG)',".htm",721);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (721,"2002-09-01",155,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (853,'Liaison Statement from SC 29/WG 11 to IETF on Carriage of MPEG-4 Content on IP Networks',".txt",722);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (722,"2002-09-01",156,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (854,'Request for the assignment of a reserved label value of 14 for MPLS OAM packet identification',".txt",723);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (723,"2002-07-01",113," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)",1,NULL," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (855,'Response to Communication from IETF on MPLS OAM packet identification',".txt",724);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (724,"2002-07-01",113," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)",1,NULL," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (856,'SG 13 work on interworking with MPLS',".txt",725);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (725,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (857,'ATM-MPLS Interworking activities in ITU-T',".txt",726);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (726,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (858,'Voice Services over MPLS',".txt",727);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (727,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (859,'AVT WG''s response to SC 29/WG 11 to IETF on the Carriage of MPEG-4 Content on IP Networks',".txt",728);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (728,"2002-06-01",153,"SC 29/WG11",1,NULL,"SC 29/WG11");
insert into uploads (file_id,file_title,file_extension,detail_id) values (860,'3GPP Diameter Charging &amp; Credit Control Application',".htm",729);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (729,"2002-06-01",99,"AAA WG Chairs",1,NULL,"AAA WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (861,'Communication re: SIP - BICC/ISUP Interworking',".txt",730);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (730,"2002-06-01",70,"SIP aand SIPPING WGs",1,NULL,"SIP aand SIPPING WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (862,'Appointment of Eric Edwards as Liaison',".txt",731);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (731,"2002-05-01",157,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (863,'Optical Intra-Carrier Network-Network Interface project',".html",732);
insert into uploads (file_id,file_title,file_extension,detail_id) values (864,'OIF Initial Requirements',".html",732);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (732,"2002-05-01",25,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (865,'Response to clarification given on usability of Sigtran in G.799.1',".htm",733);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (733,"2002-05-01",73,"Lyndon Ong (lyong@ciena.com)",1,NULL,"Lyndon Ong (lyong@ciena.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (866,'Liaison Statement from SC 29/WG 11 to IETF on the Carriage of MPEG-4 Content on IP Networks',".htm",734);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (734,"2002-05-01",158,"AVT WG",1,NULL,"AVT WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (867,'ENUM LIAISON ON IAB INSTRUCTIONS TO RIPE-NCC ',".htm",735);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (735,"2002-05-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (868,'APPROVAL OF INTERIM PROCEDURES AND ASSURANCES OF STABILITY',".htm",736);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (736,"2002-05-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (869,' Communication Statement to IETF CCAMP Working Group on signalling protocol work in Q. 14/15',".html",737);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (737,"2002-05-01",73,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (870,' Communication Statement to Optical Internetworking Forum (OIF) on automatic discovery work in Q.14/15',".html",738);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (738,"2002-05-01",73,"Optical Internetworking Forum (OIF) Architecture and Signalling WGs CC: IETF ccamp Working Group",1,NULL,"Optical Internetworking Forum (OIF) Architecture and Signalling WGs CC: IETF ccamp Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (871,'ENUM Liaison',".html",739);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (739,"2002-04-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (872,'Additional input regarding the use of M.3100 probable causes for the ITU Alarm MIB',".txt",740);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (740,"2002-04-01",66,"DISMAN WG",1,NULL,"DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (873,'Response to "Communication on the status of the request on the assignment of a reserved label value for MPLS OAM packet identification"',".txt",741);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (741,"2002-04-01",159,"Completes action above Scott Bradner, Area co-Director (sob@harvard.edu)",1,NULL,"Completes action above Scott Bradner, Area co-Director (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (874,'Liaison Statement to IETF on status of ECTP project',".txt",742);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (742,"2002-03-01",68,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (875,'ITU-SG16 comments on draft-parsons-itu-t38-reg-00.txt',".txt",743);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (743,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (876,'ITU-SG16 comments on draft-mule-sip-t38callflows-02.txt',".txt",744);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (744,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (877,'ITU-SG16 new question on Emergency Telecommunications Service (ETS)',".txt",745);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (745,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (878,'Liaison Statement from SC 29/WG 11 to IETF on Transport of MPEG-4 Content over IP [SC 29/WG 11 N 4663]',".txt",746);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (746,"2002-03-01",158,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (879,'Liaison Statement from SC 29/WG 1 to IETF, seeking IETF contributions to JPEG 2000 Part 9 JPIP [SC 29/WG 1 N 2551]',".txt",747);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (747,"2002-03-01",160,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (880,'Memo from ITU-T Study Group 13 requesting assignment of a reserved label value for MPLS OAM packet identification',".txt",748);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (748,"2002-02-01",113," Scott Bradner (sob@harvard.edu) Done",1,NULL," Scott Bradner (sob@harvard.edu) Done");
insert into uploads (file_id,file_title,file_extension,detail_id) values (881,' Detector-Controller Interface (DCI)',".html",749);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (749,"2002-02-01",73,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (882,'Memo from ATM Forum requesting status of specific documents',".txt",750);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (750,"2002-02-01",4,"Tom Taylor (taylor@nortelnetworks.com), Megaco WG Chair",1,NULL,"Tom Taylor (taylor@nortelnetworks.com), Megaco WG Chair");
insert into uploads (file_id,file_title,file_extension,detail_id) values (883,'Response to above memo from ATM Forum',".txt",751);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (751,"2002-02-01",4,"DONE",1,NULL,"DONE");
insert into uploads (file_id,file_title,file_extension,detail_id) values (884,'Memo from ATM Forum requesting comments on version 2 of their ATM-MPLS-ATM Network Interworking specification.',".html",752);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (752,"2002-02-01",4," Danny McPherson, Luca Martini (danny@tcb.net,luca@level3.net), PWE3 WG Chairs",1,NULL," Danny McPherson, Luca Martini (danny@tcb.net,luca@level3.net), PWE3 WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (885,'Communication Statement to IETF CCAMP Working Group on signalling protocol work in Q.14/15',".html",753);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (753,"2002-02-01",161,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs",1,NULL,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (886,'Communication Statement to IETF CCAMP Working Group on Virtual Backplane Interface (VBI) in Q.15',".html",754);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (754,"2002-02-01",162,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs",1,NULL,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (887,'Letter from IEEE 802.11 to IETF/IESG',".txt",755);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (755,"2002-02-01",101,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (888,'liaison statement to IETF (SC 29 N 4559 and 4561)',".txt",756);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (756,"2001-12-01",163,"Harald Alvestrand",1,NULL,"Harald Alvestrand");
insert into uploads (file_id,file_title,file_extension,detail_id) values (889,'Liaison Statement to the IETF AVT Working Group on MPEG-4 on IP',".htm",757);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (757,"2001-12-01",164,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (890,'Liaison Letter to IETF regarding JVT Video Packetization',".htm",758);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (758,"2001-12-01",165,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (891,'CODING OF MOVING PICTURES AND ASSOCIATED AUDIO INFORMATION',".htm",759);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (759,"2001-12-01",163,"Harald Alvestrand",1,NULL,"Harald Alvestrand");
insert into uploads (file_id,file_title,file_extension,detail_id) values (892,'Sigtran WG response to ITU-T SG15',".txt",760);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (760,"2001-12-01",166,"(lyong@ciena.com)Lyndon Ong",1,NULL,"(lyong@ciena.com)Lyndon Ong");
insert into uploads (file_id,file_title,file_extension,detail_id) values (893,'Memo from ITU-T Study Group 7 to the SMIng Working Group',".htm",761);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (761,"2001-12-01",167,"(bwijnen@lucent.com) Bert Wijnen",1,NULL,"(bwijnen@lucent.com) Bert Wijnen");
insert into uploads (file_id,file_title,file_extension,detail_id) values (894,' New Recommendations for Automatically Switched Optical Networks',".txt",762);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (762,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (895,' Optical Transport Networks &amp; Technologies Standardization Work Plan, Issue 1',".txt",763);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (763,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (896,'SDH Signal and Group Structures',".txt",764);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (764,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (897,' Request for comments on G.799.1 -- handling of Signalling System No.7 associated signalling links by a TIGIN gateway',".txt",765);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (765,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (898,' Liaison Statement regarding Digital Rights Standards work in the Internet Research Task Force',".htm",766);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (766,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (899,' Intellectual Property Management and Protection in MPEG Standards',".htm",767);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (767,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (900,' Re-issue of the Call for Requirements for a Rights Data Dictionary and a Rights Expression Language',".htm",768);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (768,"2001-03-01",169,"(sob@harvard.edu)Scott Bradner",1,NULL,"(sob@harvard.edu)Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (901,' MPEG-21 Requirements for a Rights Data Dictionary and a Rights Expression Language',".txt",769);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (769,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (902,'DRAFT REVISED ITU-T RECOMMENDATION X.85/Y.1321: "IP OVER SDH USING LAPS" (Temporary Document 2066/Rev.1)',".htm",770);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (770,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (903,'DRAFT AMENDMENT 1 TO ITU-T RECOMMENDATION X.85/Y.1321 (2000) (Temporary Document 2045/Rev.3)',".htm",771);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (771,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (904,'RESPONSE TO COMMENTS ON X.85/Y.1321 (Temporary Document 2031/Rev.3)',".htm",772);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (772,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (905,'REVISED DRAFT TEXT OF THE ECTP SPECIFICATION FOR ITU-T CONSENT AND JTC 1 FCD BALLOT  (Temporary Document 2032/Rev.2)',".htm",773);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (773,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (906,'REQUEST FOR CONSIDERATION OF LATEST TEXT OF ECTP (Temporary Document 2058/Rev.1)',".htm",774);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (774,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (907,'COMMUNICATION TO IETF REGARDING ALLOCATION OF IANA INTERNET CODE POINTS FOR USE IN NSAP ADDRESSES (Temporary Document 1018/Rev.1)',".htm",775);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (775,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (908,'Amendment 1: Addition of the Internet protocol address format identifier (Amendment to X.213)',".htm",776);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (776,"2001-02-01",167,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (909,'COMMUNICATION TO ISOC ON IANA REGISTRATIONS FOR REC. T. 38 ANNEX D',".txt",777);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (777,"2000-02-01",171,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (910,'Cooperative Agreement Between the Internet Society and the International Organization for Standardization / International Electrotechnical Committee 1 / Sub Committee 6 (ISO/IEC JTC1/SC6)',".txt",778);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (778,"1995-01-01",172,"ISOC",1,NULL,"ISOC");
